### PR TITLE
Increase Ollama and LM Studio timeout

### LINKED ISSUE #1681: Hardcoded 300-second API timeout makes local LLMs (Ollama/LM Studio) unusable
### Description

Bug description
The Kilo Code extension consistently terminates API requests to local LLM providers (tested with both Ollama and LM Studio) after a fixed 300-second (5-minute) timeout. This timeout appears to be hardcoded and is not affected by any attempted configurations in settings.json.

This behavior makes it impossible to use powerful local models (like QWEN3-coder) for complex tasks, as their inference time can legitimately exceed 5 minutes.

Environment
Kilo Code Version: 4.70.2 on vscode
Operating System: macOS
Hardware: MacBook Pro M4 Max, 64GB RAM
Local LLM Provider: Ollama and LM Studio (issue occurs with both)
LLM Model: QWEN3-coder-30B-1M

Steps to Reproduce
Configure a local LLM provider in Kilo Code (either Ollama or LM Studio).
Load a large, powerful model (e.g., QWEN3-coder).
Submit a complex prompt that requires significant inference time.
Wait for 300 seconds.

Actual Behavior
After exactly 300 seconds, the request fails with a client-side timeout error. The error messages vary depending on the provider:

With Ollama:
API Request Failed: Ollama request Timed out after 300 seconds

With LM Studio:
API Streaming Failed: Please check the LM Studio developer logs to debug what went wrong. You may need to load the model with a larger context length to work with Kilo Code's prompts.
Expected Behavior
The request should continue until the model has finished generating a complete response, without being interrupted by an arbitrary client-side timeout. Ideally, this timeout should be user-configurable.

Analysis and Additional Context
The fact that the issue persists identically after switching the backend from Ollama to LM Studio confirms that the 300-second timeout is initiated by Kilo Code.

This is further confirmed by the server logs (both Ollama and LM Studio), which show a client disconnected message at the 300-second mark, indicating that the client actively closed the connection while the server was still processing the request.    

Configuration attempts via settings.json (using keys like continue.requestOptions.timeout) have had no effect, which strongly suggests a hardcoded value.

Suggested Solution
Expose a configurable timeout setting: The best solution would be to add a setting in settings.json that allows users to define their own API request timeout duration (e.g., kilocode.requestTimeout).
Increase the default value: Alternatively, significantly increasing the default timeout for local providers (e.g., to 20 or 30 minutes) would solve the problem for the majority of use cases.

### PR DESCRIPTION
**Pull request by chrarnoldus**
Fixes https://github.com/Kilo-Org/kilocode/issues/1681

### CODE REVIEW

**Review by hassoncs — APPROVED** [review]
Code looks fine to me! `undici` seems sort of a heavy dep for this, but if it works, it works for me 🤷

File: src/api/providers/kilocode/fetchWithTimeout.ts [hunk 1]
```diff
@@ -0,0 +1,13 @@
...
+export function fetchWithTimeout(timeoutMs: number): typeof fetch {
+	const agent = new undici.Agent({ headersTimeout: timeoutMs, bodyTimeout: timeoutMs })
+	return (input, init) =>
+		undici.fetch(
+			input as undici.RequestInfo,
+			{
+				...init,
+				dispatcher: agent,
+			} as undici.RequestInit,
+		) as unknown as Promise<Response>
```
Comment (hassoncs) [inline src/api/providers/kilocode/fetchWithTimeout.ts:12]: #nit is it possible to type this with official undici types?

**Comment by chrarnoldus** [comment]
> Code looks fine to me! `undici` seems sort of a heavy dep for this, but if it works, it works for me 🤷

If you have a better idea I would love to hear it. It's very strange to me you can't override the timeout on the default fetch.

File: src/api/providers/kilocode/fetchWithTimeout.ts (hunk 1 above)
Comment (chrarnoldus) [reply src/api/providers/kilocode/fetchWithTimeout.ts:12]: No, then you move the problem to the call site.
