### PR TITLE
Fix edit project MCP button not opening file

### LINKED ISSUE #944: Can't open project MCP file on WSL2
### Description

But MCP installed and work and i can open file by hand. So problem with a button.

### PR DESCRIPTION
**Pull request by IAmABear**
## Context

Fixes the `Edit Project MCP` button not opening the file.

Fixes #944 

## Implementation

Add script to actually open the file after checking if the file exists.

## How to Test

- Open a project
- Go to the KiloCode extension -> Settings -> MCP Servers -> Installed
- Click on the `Edit Project MCP` button
- Either opens the existing settings or creates a new file

### CODE REVIEW

File: src/core/webview/webviewMessageHandler.ts [hunk 1]
```diff
@@ -632,6 +632,8 @@ export const webviewMessageHandler = async (
 				if (!exists) {
 					await safeWriteJson(mcpPath, { mcpServers: {} })
 				}
+
+				openFile(mcpPath) // kilocode_change
```
Comment (chrarnoldus) [inline src/core/webview/webviewMessageHandler.ts]:
```suggestion
				openFile(mcpPath)
```

This is also here in Roo: https://github.com/RooCodeInc/Roo-Code/blob/7ae74404f4197681e1847d368ecf07b365116e5e/src/core/webview/webviewMessageHandler.ts#L618

**Review by chrarnoldus — APPROVED** [review]
