### PR TITLE
CLI - Debug Commands //  Kitty Proto Improvements

### LINKED ISSUE #3472: Shift+enter submits in alacritty
### Plugin Type

Kilo Code CLI

### App Version

0.0.15

### Description

When using [alacritty](https://github.com/alacritty/alacritty), shift+enter submits instead of creating a new line.

### Reproduction steps

1. open the cli
2. type in "asdf"
3. press shift+enter

### Provider

Kilo Code

### Model

Claude Sonnet 4.5

### System Information

Manjaro, i3

### PR DESCRIPTION
**Pull request by catrielmuller**
## Context

Related: #3495 
Resolve: #3472 

This PR adds debug commands for the Kilo Code CLI and improves the Kitty keyboard protocol implementation. The changes enhance debugging capabilities for system compatibility and keyboard input issues.

## Implementation

- Added debug os command to display comprehensive system, hardware, and environment information
- Added debug keyboard command for interactive keyboard event debugging
- Fixed Kitty protocol initialization to use only flag 1 for maximum terminal compatibility
- Adjusted default escapeCodeTimeout from 0 to 500ms to properly parse Kitty protocol sequences

## Screenshots

image

Alacritty
image

## How to Test

```bash
kilocode debug os

Kilo Code - OS Debug Tool

=== Operating System ===
Name:           Linux 6.12
Platform:       linux
Type:           Linux
Release:        6.12.57
Architecture:   x64
WSL:            No

=== Hardware ===
CPU:            AMD Ryzen 9 5950X 16-Core Processor
Cores:          32
Total Memory:   62.70 GB
Free Memory:    36.06 GB
Uptime:         2h 59m

=== Environment ===
Node Version:   v20.19.2
Shell:          /run/current-system/sw/bin/zsh
Terminal:       ghostty
TERM_PROGRAM:   ghostty
COLORTERM:      truecolor
Display Server: Wayland
DISPLAY:        :0
WAYLAND_DISPLAY: wayland-0
Session Type:   wayland
Desktop:        GNOME

=== Locale ===
Language:       en_US.UTF-8
Timezone:       America/Cordoba
Encoding:       utf8

=== Linux Specific ===
Distribution:   NixOS 25.11 (Xantusia)
Kernel:         6.12.57
glibc:          ldd (GNU libc) 2.40

=== Process Information ===
PID:            457763
Parent PID:     457752
Working Dir:    /home/catrielmuller/Dev/Kilo-Org/kilocode/cli
Executable:     /nix/store/4qx33yfkway214mhlgq3ph4gnfdp32ah-nodejs-20.19.2/bin/node
Arguments:      debug os
```
Interactive Keyboard debug:
```bash
kilocode debug keyboard
```
image

### CODE REVIEW

File: cli/src/debug/keyboard/KeyboardDebugUI.tsx [hunk 1]
```diff
@@ -0,0 +1,235 @@
...
+			}
+			return char
+		})
+		.join("")
+}
+
+/**
+ * Format timestamp to HH:MM:SS.mmm
+ */
+function formatTimestamp(date: Date): string {
```
Comment (iscekic) [inline cli/src/debug/keyboard/KeyboardDebugUI.tsx:45]: Do we have a date library in the cli?

**Review by iscekic — APPROVED** [review]
