### PR TITLE
fix: start CLI backend at extension activation so autocomplete works without opening a tab

### LINKED ISSUE #6776: Autocomplete does not work until the kilo extension tab is opened

### PR DESCRIPTION
**Pull request by markijbema**
## Summary

Fixes https://github.com/Kilo-Org/kilocode/issues/6776

Three changes that together fix autocomplete not working until a Kilo sidebar/tab is opened:

1. **Eager CLI backend startup** — Call `connectionService.connect()` during `activate()` so the `kilo serve` process starts immediately, giving autocomplete a working backend from the moment the extension loads
2. **`onStartupFinished` activation event** — Without this, `activate()` itself never ran until the sidebar was shown. The eager `connect()` was dead code.
3. **Idempotent provider registration** — The constructor's `load()` and the `onStateChange` handler's `load()` raced during startup, causing unnecessary dispose/re-register cycles on the inline completion provider. Made `ensureInlineCompletionProviderRegistration` compare desired vs current state and skip when already correct.

## Problem

Autocomplete was registered as an `InlineCompletionItemProvider` during `activate()`, but had two blocking issues:
- `activate()` never ran without the sidebar open (`activationEvents` was empty)
- Even with eager activation, two concurrent `load()` calls could interleave and churn the provider registration

## Changes

- `packages/kilo-vscode/package.json` — Add `onStartupFinished` to `activationEvents`
- `packages/kilo-vscode/src/extension.ts` — Eagerly call `connectionService.connect()` (guarded by `enableAutoTrigger` setting), reload autocomplete on backend connect
- `packages/kilo-vscode/src/services/autocomplete/AutocompleteServiceManager.ts` — Replace `updateInlineCompletionProviderRegistration` with idempotent `ensureInlineCompletionProviderRegistration`

### CODE REVIEW

File: packages/kilo-vscode/src/services/cli-backend/connection-service.ts [hunk 1]
```diff
@@ -175,6 +175,20 @@ export class KiloConnectionService {
     }
   }
 
+  /**
+   * Start the CLI backend if autocomplete is enabled and a workspace folder exists.
+   * Idempotent — safe to call from multiple sites (activate, config change listener, etc.).
+   */
+  ensureBackendForAutocomplete(): void {
+    const enabled =
+      vscode.workspace.getConfiguration("kilo-code.new.autocomplete").get<boolean>("enableAutoTrigger") ?? true
```
Comment (marius-kilocode) [inline packages/kilo-vscode/src/services/cli-backend/connection-service.ts]: Should we access `vscode.workspace` in the service? This smells to me

File: packages/kilo-vscode/package.json [hunk 2]
```diff
@@ -45,13 +45,7 @@
     "kilocode"
   ],
   "activationEvents": [
-    "onWebviewPanel:kilo-code.new.AgentManagerPanel",
-    "onWebviewPanel:kilo-code.new.TabPanel",
-    "onWebviewPanel:kilo-code.new.settingsPanel",
-    "onWebviewPanel:kilo-code.new.profilePanel",
-    "onWebviewPanel:kilo-code.new.marketplacePanel",
-    "onWebviewPanel:kilo-code.new.DiffViewerPanel",
-    "onWebviewPanel:kilo-code.new.SubAgentViewerPanel"
```
Comment (marius-kilocode) [inline packages/kilo-vscode/package.json:54]: Why is this removed?

**Review by marius-kilocode — APPROVED** [review]

File: packages/kilo-vscode/package.json (hunk 2 above)
Comment (markijbema) [reply packages/kilo-vscode/package.json:54]: because we now start all this earlier
