### PR TITLE
fix(vscode): preview pasted images in chat input

### LINKED ISSUE #7049: [FEATURE]: Clicking on an image pasted into the chat input should open it in a preview so the user can easily see it in actual size
### Feature hasn't been suggested before.

- [x] I have verified this feature I'm about to request hasn't been suggested before.

### Describe the enhancement you want to request

If you paste an image into the chat session input, and then click on it, nothing happens. It would be nice for a larger view of this to pop open in vscode. This way the user can easily see it and use it as a reference when adding text input to go along with it. 

This also used to work this way in the old extension.

### PR DESCRIPTION
**Pull request by Githubguy132010**
Fixes #7049 

## Context

Restore the old extension behavior where clicking an image pasted into the chat input opens a larger VS Code preview, so users can inspect the attachment at actual size while composing their prompt.

## Implementation

- added a new `previewImage` webview message for attached image thumbnails in both the main chat input and Agent Manager dialog
- handled `previewImage` in `KiloProvider` by parsing the image data URL, writing a preview file into extension storage, and opening it with VS Code's built-in image preview with a fallback to `vscode.open`
- extracted the preview parsing/path helpers into `src/image-preview.ts` and added focused unit coverage plus the minimal VS Code fs mocks needed by the tests

## Screenshots

| before | after |
| ------ | ----- |
| image | Schermafdruk van 2026-03-14 18-50-25 |

## How to Test

- open the VS Code extension chat input or Agent Manager new worktree dialog
- paste or drag in a PNG/JPEG/GIF/WebP image so it appears as an attachment thumbnail
- click the thumbnail
- verify VS Code opens the image in a larger preview editor
- run `bun test tests/unit/image-preview.test.ts tests/unit/kilo-provider-session-refresh.test.ts` from `packages/kilo-vscode`
- run `bun turbo typecheck` from the repo root

## Get in Touch

thomas07374

### CODE REVIEW

File: packages/kilo-vscode/src/KiloProvider.ts [hunk 1]
```diff
@@ -1810,6 +1814,25 @@ export class KiloProvider implements vscode.WebviewViewProvider, TelemetryProper
    * a worktree path registered via setSessionDirectory), falling back to workspace root.
    * Absolute paths (Unix `/…` or Windows `C:\…`) are used as-is.
    */
+  private handlePreviewImage(dataUrl: string, filename: string): void {
```
Comment (marius-kilocode) [inline packages/kilo-vscode/src/KiloProvider.ts]: Injecting `handlePreviewImage` here makes the documentation of `handleOpenFile` irrelevant. Please define the function above the documentation.

File: packages/kilo-vscode/src/KiloProvider.ts [hunk 2]
```diff
@@ -1810,6 +1814,25 @@ export class KiloProvider implements vscode.WebviewViewProvider, TelemetryProper
...
+    const dir = this.extensionContext?.globalStorageUri
+    if (!dir) return
+
+    const img = parseImage(dataUrl, filename)
+    if (!img) return
+
+    const uri = vscode.Uri.joinPath(dir, buildPreviewPath(img.name, Date.now()))
+    const open = () =>
```
Comment (marius-kilocode) [inline packages/kilo-vscode/src/KiloProvider.ts:1837]: I tested this in the side bar and agent manager. Unfortunately it only works in the sidebar. But clicking in the agent manager doesn't work. Please test all code paths manually that the PR states to implement.

File: packages/kilo-vscode/src/KiloProvider.ts [hunk 3]
```diff
@@ -1810,6 +1814,25 @@ export class KiloProvider implements vscode.WebviewViewProvider, TelemetryProper
    * a worktree path registered via setSessionDirectory), falling back to workspace root.
    * Absolute paths (Unix `/…` or Windows `C:\…`) are used as-is.
    */
+  private handlePreviewImage(dataUrl: string, filename: string): void {
+    const dir = this.extensionContext?.globalStorageUri
```
Comment (marius-kilocode) [inline packages/kilo-vscode/src/KiloProvider.ts:1812]: Will the files accumulate in `globalStorageUri`? How did we do this in `https://github.com/Kilo-Org/kilocode-legacy`?

File: packages/kilo-vscode/src/KiloProvider.ts (hunk 2 above)
Comment (Githubguy132010) [reply packages/kilo-vscode/src/KiloProvider.ts:1837]: Fixed the Agent Manager path as well. The Agent Manager interceptor was swallowing `previewImage` instead of forwarding it to `KiloProvider`, so clicks there never reached the preview handler. I added `previewImage` to the agent-manager message contract and now pass it through unchanged, then reran `bun run test tests/unit/image-preview.test.ts`, `bun run format`, and the branch push also completed `bun turbo typecheck` via the push hook.

File: packages/kilo-vscode/src/KiloProvider.ts (hunk 1 above)
Comment (Githubguy132010) [reply packages/kilo-vscode/src/KiloProvider.ts]: Moved `handlePreviewImage()` above the `handleOpenFile()` docblock so the open-file documentation stays attached to the right method.

File: packages/kilo-vscode/src/KiloProvider.ts (hunk 3 above)
Comment (Githubguy132010) [reply packages/kilo-vscode/src/KiloProvider.ts:1812]: It would have accumulated before this change. I added bounded cleanup so we keep only the newest 20 files in `globalStorageUri/image-preview/` after each preview write, which avoids unbounded growth while still keeping previews available for the open editor. I could not find an equivalent implementation in `kilocode-legacy` via GitHub code search, so this cleanup is implemented directly here.

**Comment by Githubguy132010** [comment]
Addressed the cleanup failure case in . Stale preview deletions are now best-effort, so a failed  only logs a warning and no longer prevents the newly selected image from opening. Pushed in 33241e72c4.

File: packages/kilo-vscode/src/KiloProvider.ts [hunk 4]
```diff
@@ -1804,6 +1808,37 @@ export class KiloProvider implements vscode.WebviewViewProvider, TelemetryProper
...
+    const img = parseImage(dataUrl, filename)
+    if (!img) return
+
+    const root = vscode.Uri.joinPath(dir, getPreviewDir())
+    const uri = vscode.Uri.joinPath(dir, buildPreviewPath(img.name, Date.now()))
+    const clean = () =>
+      vscode.workspace.fs.readDirectory(root).then(
+        (items) => {
+          const stale = trimEntries(items.map(([name]) => ({ path: name })))
+          return Promise.all(
```
[the remark this answers is not in the document]
Comment (Githubguy132010) [reply packages/kilo-vscode/src/KiloProvider.ts:1824]: Handled by making stale preview deletion best-effort. Each delete now resolves independently and logs a warning on failure, so cleanup no longer blocks opening the newly clicked image.

**Review by marius-kilocode — APPROVED** [review]

**Comment by marius-kilocode** [comment]
@Githubguy132010 I merged it. Nice contribution!

**Comment by Githubguy132010** [comment]
No problem!
