### PR TITLE
fix(extension): allow killing detached processes

### LINKED ISSUE #2653: Kill Command Button not able to kill
### Description

I am currently using the vscode with version: 4.97.1 (d17e651d) in m1 mac.
Before update to this version, I was able to kill command to proceed normally, now I find that after clicked the `kill command`, command still running and asking terminal or run without stopping it. 
I have terminate the process in another terminal. After the termination, the task can proceed.

### PR DESCRIPTION
**Pull request by hdcodedev**
## Context

Fixes #2653

The "Kill Command" button would fail to terminate a process if the user had previously clicked "Proceed While Running". This occurred due to two issues:

1. **`TerminalProcess.abort()` checked `isListening`**: The termination signal (`\x03`) was only sent if `isListening` was true. Clicking "Proceed While Running" calls `continue()`, which sets `isListening` to false.

2. **`task.terminalProcess` was cleared too early**: When "Proceed While Running" is clicked, `process.continue()` emits a "continue" event which resolves the process promise. This triggered the `finally` block in `executeCommandInTerminal()` which set `task.terminalProcess = undefined`, making subsequent kill attempts do nothing.

### `TerminalProcess.ts`
- Removed the `if (this.isListening)` check from `abort()`. The termination signal is now sent unconditionally.
- Implemented safe dereferencing (`terminalRef.deref()`) to prevent crashes if the terminal has been garbage collected.

### `ExecuteCommandTool.ts`
- Added `if (!runInBackground)` check before clearing `task.terminalProcess` in the finally blocks.
- This preserves the process reference for background processes, allowing the kill button to still access it.

### Tests
- Added unit test verifying `abort()` works after `continue()` is called.
- Verified that `sendText` is called exactly once to avoid signal spamming.
- Added safety test ensuring `abort()` doesn't throw if terminal is undefined.
- Added `vi.clearAllMocks()` to `beforeEach` to ensure clean state between tests.

## How to Test

1. Start Kilo Code and ask it to run a long-running command that produces output:
   ```bash
   run ping -c 100 localhost
   ```
   > **Note:** The "Proceed While Running" button only appears if the command produces visible output. Commands like `sleep 60` (without echo) will not trigger the button.

2. Click **"Run"** to approve the command.

3. Wait for output to appear, then click **"Proceed While Running"**.

4. Click the **⊗ (kill) button** next to the PID.

5. **Verify:** The terminal process terminates successfully.
   - In a separate terminal, run: `ps -p <PID>` - should show no process

### Before (Bug)
https://github.com/user-attachments/assets/16f319c4-6652-4f20-9dc1-8f3c5629b27b

### After (Fix)
https://github.com/user-attachments/assets/1a068a01-8fa5-46ac-be28-cbc16e23e527

### CODE REVIEW

**Comment by marius-kilocode** [comment]
@hdcodedev I can't really reproduce this with the CLI. Do you have a better example todo so?

**Comment by hdcodedev** [comment]
I'll test more today and update you with the results.

**Comment by hdcodedev** [comment]
@marius-kilocode You're right, `fix(cli)` was misleading, I've renamed it to `fix(extension)`.
The "Proceed While Running" button requires command output to appear, which is why `sleep` didn't trigger it. I've updated the PR description with:
- Correct title (`fix(extension)`)
- Reliable reproduction steps (using `ping`)
- Full fix details (we found a second root cause where the process ref was cleared too early)
- **Demo videos**  (Please check PR description)

Update: I verified this fix in the VS Code extension. I haven't checked if a similar issue affects the @kilocode/cli

File: src/integrations/terminal/TerminalProcess.ts [hunk 1]
```diff
@@ -265,10 +265,10 @@ export class TerminalProcess extends BaseTerminalProcess {
...
 	public override abort() {
-		if (this.isListening) {
-			// Send SIGINT using CTRL+C
-			this.terminal.terminal.sendText("\x03")
-		}
+		// User-initiated kill must always attempt to interrupt the process.
+		// Listening state does not reflect process liveness.
+		const terminal = this.terminalRef.deref()
+		terminal?.terminal?.sendText("\x03")
 	}
```
Comment (hdcodedev) [inline src/integrations/terminal/TerminalProcess.ts:264]: **Why this change is needed**
When a user clicks “Proceed/Continue,” we intentionally stop listening to terminal output so the UI stays quiet. That sets isListening = false and removes the line listeners, but the process is still running.
The kill button calls abort(), and the old guard (if (isListening)) meant we never sent Ctrl‑C after Continue. That’s why the kill button looked like a no‑op.

**What this fixes**

We now send Ctrl‑C unconditionally on user‑initiated abort. Listening state is about UI streaming, not process liveness. This makes “Kill” work even after “Proceed/Continue,” which matches user intent and doesn’t affect normal execution.

File: src/core/tools/ExecuteCommandTool.ts [hunk 2]
```diff
@@ -308,14 +308,20 @@ export async function executeCommandInTerminal(
 				clearTimeout(timeoutId)
 			}
 
-			task.terminalProcess = undefined
+			// Don't clear if running in background - user may still want to kill it
+			if (!runInBackground) {
+				task.terminalProcess = undefined
+			}
```
Comment (hdcodedev) [inline src/core/tools/ExecuteCommandTool.ts:314]: **Why keep task.terminalProcess when running in background**

When the user clicks “Proceed/Continue,” we allow the command to keep running in the terminal. At that point the promise resolves and we enter finally, which used to clear task.terminalProcess.
That wiped the only handle the kill button uses, so later aborts did nothing even though the process was still alive.

By only clearing the reference when not running in background, we keep the handle around so the kill button can still terminate the process after “Proceed/Continue.”

**Review by kevinvandijk — APPROVED** [review]
Lgtm! Thanks!
