### PR TITLE
CLI - Tasks History

### LINKED ISSUE #2995: Implement a /history command
### Plugin Type

Kilo Code CLI

### App Version

alpha

### Description

Users should be able to continue where they've left off in older sessions just like they can in the VS Code extension.

`/history` should autocomplete with a list of past sessions, and selecting an item should rewrite the current session.

### Reproduction steps

`/history` should autocomplete with a list of past sessions, and selecting an item should rewrite the current session.

### Provider

_No response_

### Model

_No response_

### System Information

_No response_

### PR DESCRIPTION
**Pull request by catrielmuller**
## Context

Resolve: #2995 

## Implementation

- '/tasks' command with subcommands
- Refactor clear screen to improve the experience
- Automatic fetch the fist page to speedup the first '/tasks'
- Util `generateMessage` to generate unique ids

## Screenshots

image

image

image

image

image

image

image

image

image
 
image

image

image

image

image

image

### CODE REVIEW

File: cli/src/ui/utils/messages.ts [hunk 1]
```diff
@@ -0,0 +1,8 @@
+export const generateMessage = () => {
+	const now = Date.now()
+	const uniqueSuffix = Math.floor(Math.random() * 10000)
```
Comment (iscekic) [inline cli/src/ui/utils/messages.ts:3]: We can be slightly more robust by having a counter variable above and then just using/incrementing the counter instead of generating a random suffix.

File: cli/src/state/atoms/taskHistory.ts
Comment (iscekic) [inline cli/src/state/atoms/taskHistory.ts:1]: I wonder if we could simplify things by using tanstack query and having the extension be our "backend". Gut tells me we'd end up with simpler code - something to ponder, maybe not for this PR. :smile:

File: cli/src/state/atoms/effects.ts [hunk 2]
```diff
@@ -162,6 +168,35 @@ export const messageHandlerEffectAtom = atom(null, (get, set, message: Extension
 				}
 				break
 
+			case "taskHistoryResponse":
+				// Handle task history response
+				set(taskHistoryLoadingAtom, false)
+				if (message.payload) {
+					const { historyItems, pageIndex, pageCount, requestId } = message.payload as any
```
Comment (iscekic) [inline cli/src/state/atoms/effects.ts:175]: Can we cast to something non-any? :smile:

File: cli/src/commands/tasks.ts [hunk 3]
```diff
@@ -0,0 +1,608 @@
...
+	return "just now"
+}
+
+/**
+ * Format cost as a currency string
+ */
+function formatCost(cost: number): string {
+	if (cost === 0) return "$0.00"
+	if (cost < 0.01) return "<$0.01"
+	return `$${cost.toFixed(2)}`
```
Comment (iscekic) [inline cli/src/commands/tasks.ts:43]: (probably not for this PR) I wonder if we might want to use [NumberFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat) for i18n niceness (here and elsewhere). :thinking:

File: cli/src/state/atoms/taskHistory.ts
Comment (catrielmuller) [reply cli/src/state/atoms/taskHistory.ts:1]: @iscekic Me too... 
- https://jotai.org/docs/extensions/trpc
- https://gronxb.github.io/webview-bridge/

File: cli/src/state/atoms/effects.ts (hunk 2 above)
Comment (catrielmuller) [reply cli/src/state/atoms/effects.ts:175]: I created a new task to improve this situation -> https://github.com/Kilo-Org/kilocode/issues/3493

File: cli/src/commands/tasks.ts (hunk 3 above)
Comment (catrielmuller) [reply cli/src/commands/tasks.ts:43]: https://github.com/Kilo-Org/kilocode/issues/3494

File: cli/src/ui/utils/messages.ts (hunk 1 above)
Comment (catrielmuller) [reply cli/src/ui/utils/messages.ts:3]: We can add uuid to be more safe, this is a minimal workaround on the CLI. The extension shouls be send the Messages with a unique ID.
@RSO, What do you think of this?

**Review by iscekic — APPROVED** [review]
