### PR TITLE
fix: improve user message visibility with distinctive theme-aware colors

### LINKED ISSUE #5738: Usability: Skim through is Broken - Was Easy, Now Very Difficult.
### Plugin Type

VSCode Extension

### App Version

v5.4.1

### Description

Earlier version are very easy to skim though my response vs ai responses. Since >80% is ai generated text is there. Now in mentioned release, cant identiy what text I have input visually, its very difficult to skim through since every thing is same color, not at all intutive, overall it made it very difficult to use. 

Suggestion - different color for human input, to easily skim though the input.

### Reproduction steps

Switch to older verisons  - 4.x
1. perform any long task, what every human input is given, its easily to identify in the whole chat log

Switch to older verisons  - v5.4.1
1. perform any long task, what every human input is given, its very difficuly to identify the human input in the whole chat log

### Provider

_No response_

### Model

_No response_

### System Information

Mac M2 Pro

### PR DESCRIPTION
**Pull request by Githubguy132010**
## Context

Fixes #5738

User messages in chat history were difficult to distinguish from AI responses after a recent change muted the styling. This made it hard to skim through conversations and identify user input visually.

## Implementation

The root cause was commit `8b01f57172` which changed user message styling from distinctive inverted colors to muted sidebar colors, making user messages blend in with AI responses.

This fix updates the user message styling in `ChatRow.tsx` to use VSCode's theme-aware input validation colors:

**Before (muted, blends with UI):**
```
bg-vscode-sideBar-background text-vscode-foreground
```

**After (distinctive, theme-aware):**
```
bg-vscode-inputValidation-infoBackground text-vscode-inputValidation-infoForeground border-vscode-inputValidation-infoBorder
```

This provides:
- Distinctive visual appearance for user messages
- Theme-aware colors that work in both light and dark themes
- Subtle border for additional visual separation

## Screenshots

| before | after |
| ------ | ----- |
| User messages blended with sidebar background | User messages have distinctive info-colored background and border |

## How to Test

1. Open Kilo Code extension
2. Start a conversation with the AI
3. Send several messages back and forth
4. Observe that your user messages now have a distinctive background color that makes them easy to identify when skimming through the chat history

## Get in Touch

Discord: thomas07374

### CODE REVIEW

**Comment by lambertjosh** [comment]
Thanks @Githubguy132010 - I am checking with our designer, but I agree user input can be more distinctive. While I'm doing that, can you add the `kilocode_change` comments back to the changed lines? To minimize merge conflicts we like to keep them as targeted as possible. 

Here is a screenshot for others to see of one theme, but in general for the handful I tested it is blue'ish: 
image

**Comment by Githubguy132010** [comment]
> Thanks @Githubguy132010 - I am checking with our designer, but I agree user input can be more distinctive. While I'm doing that, can you add the `kilocode_change` comments back to the changed lines? To minimize merge conflicts we like to keep them as targeted as possible. 
> 
> Here is a screenshot for others to see of one theme, but in general for the handful I tested it is blue'ish: 
> image
> 

@lambertjosh I added back the markers as requested.

**Comment by halyna-hlynska** [comment]
@Githubguy132010 @lambertjosh just a small suggestion from my side. I agree we need to make user messages more distinctive, but the current bright blue feels a bit too strong. It competes with primary action colors (which are also blue) and draws too much attention.

I’d suggest something more subtle instead. The goal is for user messages to remain clearly distinguishable without overpowering the rest of the UI.

In the updated version, I used a softer grey-ish background for user messages. This keeps them visually separated from agent responses and doesn’t compete with primary actions like “Run”. 

[Here's link to the Figma design with updated version](https://www.figma.com/design/YpH0kLX0GHixwAaUvTvBkb/Kilo-Chat---VS-Studio?node-id=2033-1322&t=B0bEqVpNLXNZee7b-4)

And here's a screenshot
Screenshot 2026-02-12 at 10 45 46

**Comment by Githubguy132010** [comment]
@halyna-hlynska I agree your design is much better. I will implement your design from the screenshot tomorrow and push a commit.

File: webview-ui/src/components/chat/ChatRow.tsx [hunk 1]
```diff
@@ -1356,13 +1356,14 @@ export const ChatRowContent = ({
 								<User className="w-4 shrink-0" aria-label="User icon" />
 								<span style={{ fontWeight: "bold" }}>{t("chat:feedback.youSaid")}</span>
 							</div>
+							{/* kilocode_change: distinctive user message styling with theme-aware colors for better visibility */}
```
Comment (lambertjosh) [inline webview-ui/src/components/chat/ChatRow.tsx]:
```suggestion
```

We don't need this comment since the changes we are making are individually annotated.

**Comment by lambertjosh** [comment]
Thanks @Githubguy132010 @halyna-hlynska! These changes look good to me, I just cleaned up an unnecessary kilocode change comment. Merging.

image

**Review by lambertjosh — APPROVED** [review]
