### PR TITLE
fix(vscode): chat autocomplete ignores disabled setting

### LINKED ISSUE #7758: Chat Autocomplete still working even if disabled in Settings
### Description

The option is disabled in Settings, but I still get Autocomplete suggestions in the chat textarea

Image

### Plugins

_No response_

### Kilo version

_No response_

### Steps to reproduce

_No response_

### Screenshot and/or share link

_No response_

### Operating System

_No response_

### Terminal

_No response_

### PR DESCRIPTION
**Pull request by markijbema**
## Summary

- **Root cause**: `KiloProvider` had no `onDidChangeConfiguration` listener for `kilo-code.new.autocomplete`, so when the user toggled `enableChatAutocomplete` off in the settings panel (or via VS Code settings UI), the webview was never notified and the `useGhostText` hook retained the old `enabled = true` state.
- **Fix**: Add a `vscode.workspace.onDidChangeConfiguration` subscription in `resolveWebviewView()` and `resolveWebviewPanel()` that calls `sendAutocompleteSettings()` whenever the autocomplete config section changes. Registering it here (rather than inside `doInitializeConnection`) ensures the listener is active even when the provider is disconnected or in an error state.
- **Secondary fix**: Corrected the `readSettings()` fallback for `enableChatAutocomplete` from `?? true` to `?? false` to match the `package.json` declared default.

Fixes #7758

Supersedes #7916

### CODE REVIEW

File: packages/kilo-vscode/src/services/autocomplete/AutocompleteServiceManager.ts [hunk 1]
```diff
@@ -25,7 +25,7 @@ function readSettings(): AutocompleteServiceSettings {
   return {
     enableAutoTrigger: config.get<boolean>("enableAutoTrigger") ?? true,
     enableSmartInlineTaskKeybinding: config.get<boolean>("enableSmartInlineTaskKeybinding") ?? true,
-    enableChatAutocomplete: config.get<boolean>("enableChatAutocomplete") ?? true,
+    enableChatAutocomplete: config.get<boolean>("enableChatAutocomplete") ?? false,
```
Comment (markijbema) [inline packages/kilo-vscode/src/services/autocomplete/AutocompleteServiceManager.ts:28]: we dont want to change the default

**Review by chrarnoldus — APPROVED** [review]
