### PR TITLE
fix mermaid syntax errors

### LINKED ISSUE #398: Unable to render diagram error
### Add a description (be as detailed as possible)

model: `openrouter:anthropic/claude-3.7`

Image
```
Error: Parse error on line 8:
...dContent(): Promise<{text: string, copie
-----------------------^
Expecting 'STRUCT_STOP', 'MEMBER', got 'OPEN_IN_STRUCT'

```mermaid
classDiagram
    class IDE {
        +readFile(filepath: string): Promise<string>
        +readRangeInFile(filepath: string, range: Range): Promise<string>
        +getWorkspaceDirs(): Promise<string[]>
        +getRepoName(filepath: string): Promise<string | undefined>
        +getUniqueId(): Promise<string>
        +getClipboardContent(): Promise<{text: string, copiedAt: number}[]>
        +getDiff(staged: boolean): Promise<string[]>
        +gotoDefinition(params: {filepath: string, position: Position}): Promise<RangeInFile[]>
        +...other methods
    }
    class KiloCodeIDEAdapter {
        +readFile(filepath: string): Promise<string>
        +readRangeInFile(filepath: string, range: Range): Promise<string>
        +getWorkspaceDirs(): Promise<string[]>
        +...implementations of other methods
    }
    IDE <|-- KiloCodeIDEAdapter

```
```


```
Error: Parse error on line 3:
...adConfig(): Promise<{config: any | null}
-----------------------^
Expecting 'STRUCT_STOP', 'MEMBER', got 'OPEN_IN_STRUCT'

```mermaid
classDiagram
    class ConfigHandler {
        +loadConfig(): Promise<{config: any | null}>
        +reloadConfig(): Promise<void>
    }
    class KiloCodeConfigAdapter {
        +loadConfig(): Promise<{config: any | null}>
        +reloadConfig(): Promise<void>
    }
    ConfigHandler <|-- KiloCodeConfigAdapter

```
```

### PR DESCRIPTION
**Pull request by markijbema**
## Context

LLMs (especially less advanced ones) tend to make Mermaid diagrams with syntax errors

Fixes: #398, #745

## Implementation

I've created a method to fix those diagrams by deterministic operations (commonly seen syntax errors which are easy to fix without an llm) and a llm call with a specific prompt. We retry twice, but if by then it is still not rendered we again show the error, and give the user the option to try fixing it again using a button. Typically this isn't necessary though.

## Screenshots

Example of a rendering issue which wasn't fixed in two retries:
Screenshot 2025-06-24 at 15 39 44

## How to Test

Clone the react repository and open this file:
https://github.com/facebook/react/blob/main/packages/react-reconciler/src/ReactFiberWorkLoop.js

Prompt:

> please show a mermaid diagram for this file explaining what it does. Make sure it is very detailed. And if you think its detailed enough, add more details. Be sure to include exact function names with parentheses etc

Model: gemini-flash

This typically fails without this fix

### CODE REVIEW

**Comment by markijbema** [comment]
I haven't added kilocode_change markers yet; I will, but don't know if the review prompts me to move a lot of stuff around

File: src/core/prompts/utilities/mermaid.ts [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+Requirements:
+1. Return ONLY the corrected Mermaid syntax
+2. Do not include markdown code blocks or explanations
+3. Ensure the syntax is valid according to Mermaid specifications
+4. Enclose labels and edge label within double quotes even when you do not think it necessary to ensure the syntax is robust
+5. Do not point to multiple nodes with one edge, use multiple edges instead
+6. Preserve the original intent and structure as much as possible
+7. If the diagram type is unclear, default to a flowchart
+
+Corrected Mermaid code:`
```
Comment (chrarnoldus) [inline src/core/prompts/utilities/mermaid.ts:30]: This last sentence helps?

Comment (markijbema) [reply src/core/prompts/utilities/mermaid.ts:30]: How can you ever be sure; I used the LLM to scaffold a prompt, and it suggested this, and it works? I manually added 4 & 5 because i noticed they were common errors

**Comment by chrarnoldus** [comment]
Are all the try/catch necessary? At first glance it seems they were added haphazardly.

**Comment by markijbema** [comment]
Hmm, I guess Claude was being extra carefull, I removed the once Which were redundant, as far as I can see what is left is still necessary

**Comment by chrarnoldus** [comment]
> Hmm, I guess Claude was being extra carefull, I removed the once Which were redundant, as far as I can see what is left is still necessary

It is necessary based on what similar code in the codebase does or did you add any exceptions?

File: src/core/webview/webviewMessageHandler.ts [hunk 2]
```diff
@@ -1708,6 +1709,36 @@ export const webviewMessageHandler = async (
 				await provider.toggleTaskFavorite(message.text)
 			}
 			break
+		// kilocode_change start
+		case "fixMermaidSyntax":
+			if (message.text && message.requestId) {
+				try {
```
Comment (markijbema) [inline src/core/webview/webviewMessageHandler.ts:1817]: all other calls in this file are set up like this

File: webview-ui/src/services/mermaidSyntaxFixer.ts [hunk 3]
```diff
@@ -0,0 +1,140 @@
...
+	static applyDeterministicFixes(code: string): string {
+		// Fix HTML entity encoding: --&gt; should be -->
+		return code.replace(/--&gt;/g, "-->")
+	}
+
+	/**
+	 * Validates Mermaid syntax using the mermaid library
+	 */
+	static async validateSyntax(code: string): Promise<MermaidValidationResult> {
+		try {
```
Comment (markijbema) [inline webview-ui/src/services/mermaidSyntaxFixer.ts:38]: raising is how an invalid mermaid doc is detected

File: webview-ui/src/components/common/MermaidBlock.tsx [hunk 4]
```diff
@@ -150,11 +186,51 @@ export default function MermaidBlock({ code }: MermaidBlockProps) {
...
+		if (fixResult.success) {
+			setHasAutoFixed(true)
+			return { success: true }
+		}
+
+		const errorMessage = fixResult.error || t("common:mermaid.errors.fix_failed")
+		return { success: false, error: errorMessage }
+	}
+
+	// Manual fix function
```
Comment (chrarnoldus) [inline webview-ui/src/components/common/MermaidBlock.tsx]: unnecessary comment

File: webview-ui/src/services/mermaidSyntaxFixer.ts [hunk 5]
```diff
@@ -0,0 +1,140 @@
...
+				llmAttempts++
+				const fixedCode = await this.requestLLMFix(currentCode, lastError)
+
+				if (!fixedCode) {
+					finalError = "LLM failed to provide a fix"
+					break
+				}
+
+				currentCode = fixedCode
+			} catch (requestError) {
```
Comment (chrarnoldus) [inline webview-ui/src/services/mermaidSyntaxFixer.ts]: Here the errors are modeled as exceptions rather than return values because its more idiomatic?

File: src/core/webview/webviewMessageHandler.ts (hunk 2 above)
Comment (chrarnoldus) [reply src/core/webview/webviewMessageHandler.ts:1817]: which are probably all vibe coded, but ok.

File: webview-ui/src/services/mermaidSyntaxFixer.ts (hunk 5 above)
Comment (markijbema) [reply webview-ui/src/services/mermaidSyntaxFixer.ts]: I create no exceptions, i was under the impression that vscode.postMessage could fail, but apperently not, so this catch can go

**Comment by markijbema** [comment]
@chrarnoldus rebased to make sure nothing was out of sync; the last three commits are new since your latest review.

File: webview-ui/src/services/mermaidSyntaxFixer.ts [hunk 6]
```diff
@@ -0,0 +1,135 @@
...
+				isValid: false,
+				error: error instanceof Error ? error.message : "Unknown syntax error",
+			}
+		}
+	}
+
+	/**
+	 * Requests the LLM to fix the Mermaid syntax via the extension
+	 */
+	private static async requestLLMFix(code: string, error: string): Promise<string | null> {
```
Comment (chrarnoldus) [inline webview-ui/src/services/mermaidSyntaxFixer.ts]: Why is this async? Does that make sense considering you're returning the promise explicitly?

File: webview-ui/src/services/mermaidSyntaxFixer.ts [hunk 7]
```diff
@@ -0,0 +1,135 @@
...
+
+			const messageListener = (event: MessageEvent) => {
+				const message = event.data
+				if (message.type === "mermaidFixResponse" && message.requestId === requestId) {
+					cleanup()
+
+					if (message.success) {
+						resolve(message.fixedCode)
+					} else {
+						reject(new Error(message.error || "LLM fix failed"))
```
Comment (chrarnoldus) [inline webview-ui/src/services/mermaidSyntaxFixer.ts]: This is equivalent to throwing an exception when you await the promise, I think.

File: webview-ui/src/components/common/MermaidBlock.tsx [hunk 8]
```diff
@@ -86,45 +87,85 @@ interface MermaidBlockProps {
...
 		setError(null)
-	}, [code])
+		// kilocode_change start
+		setCurrentCode(originalCode)
+		setHasAutoFixed(false)
+		// kilocode_change end
+	}, [originalCode])
 
-	// 2) Debounce the actual parse/render
+	// 2) Debounce the actual parse/render with LLM-powered fixing
```
Comment (chrarnoldus) [inline webview-ui/src/components/common/MermaidBlock.tsx]: unnecessary change?

Comment (markijbema) [reply webview-ui/src/components/common/MermaidBlock.tsx]: Maybe? I did intentionally keep this because it is a bit unexpected that it does that when you're reading the code here. And when I make the PR to Roo I think this makes sense as well?

Comment (chrarnoldus) [reply webview-ui/src/components/common/MermaidBlock.tsx]: should it have kilocode_change then?

File: webview-ui/src/components/common/MermaidBlock.tsx [hunk 9]
```diff
@@ -210,12 +261,27 @@ export default function MermaidBlock({ code }: MermaidBlockProps) {
...
+							{/* kilocode_change end */}
 						</div>
 					)}
 				</div>
 			) : (
 				<MermaidButton containerRef={containerRef} code={code} isLoading={isLoading} svgToPng={svgToPng}>
-					<SvgContainer onClick={handleClick} ref={containerRef} $isLoading={isLoading}></SvgContainer>
+					<SvgContainer
+						onClick={handleClick}
+						ref={containerRef}
```
Comment (chrarnoldus) [inline webview-ui/src/components/common/MermaidBlock.tsx]: Is the ref still necessary now we're doing dangerouslySetInnerHTML?

File: webview-ui/src/components/common/MermaidBlock.tsx [hunk 10]
```diff
@@ -308,6 +374,45 @@ const CopyButton = styled.button`
 	}
 `
 
+// kilocode_change start
+const FixButton = styled.button`
```
Comment (chrarnoldus) [inline webview-ui/src/components/common/MermaidBlock.tsx]: move to separate file?

File: webview-ui/src/components/common/MermaidBlock.tsx (hunk 9 above)
Comment (markijbema) [reply webview-ui/src/components/common/MermaidBlock.tsx]: Good point, dont think so

File: webview-ui/src/components/common/MermaidBlock.tsx (hunk 8 above)
Comment (markijbema) [reply webview-ui/src/components/common/MermaidBlock.tsx]: Is that a good idea for comments?

File: webview-ui/src/components/common/MermaidBlock.tsx (hunk 10 above)
Comment (markijbema) [reply webview-ui/src/components/common/MermaidBlock.tsx]: done.

File: webview-ui/src/components/common/MermaidBlock.tsx [hunk 11]
```diff
@@ -5,8 +5,10 @@ import { useDebounceEffect } from "@src/utils/useDebounceEffect"
 import { vscode } from "@src/utils/vscode"
 import { useAppTranslation } from "@src/i18n/TranslationContext"
 import { useCopyToClipboard } from "@src/utils/clipboard"
+import { MermaidSyntaxFixer } from "@src/services/mermaidSyntaxFixer" // kilocode_change
 import CodeBlock from "./CodeBlock"
 import { MermaidButton } from "@/components/common/MermaidButton"
+import { MermaidFixButton } from "@/components/common/MermaidFixButton"
```
Comment (chrarnoldus) [inline webview-ui/src/components/common/MermaidBlock.tsx]:
```suggestion
import { MermaidFixButton } from "@/components/common/MermaidFixButton" // kilocode_change
```

File: webview-ui/src/components/common/MermaidFixButton.tsx [hunk 12]
```diff
@@ -0,0 +1,38 @@
+import styled from "styled-components"
```
Comment (chrarnoldus) [inline webview-ui/src/components/common/MermaidFixButton.tsx:2]:
```suggestion
 // kilocode_change file added
import styled from "styled-components"
```

File: webview-ui/src/services/mermaidSyntaxFixer.ts [hunk 13]
```diff
@@ -0,0 +1,154 @@
+import { vscode } from "@src/utils/vscode"
```
Comment (chrarnoldus) [inline webview-ui/src/services/mermaidSyntaxFixer.ts:2]:
```suggestion
// kilocode_change file added
import { vscode } from "@src/utils/vscode"
```

File: webview-ui/src/components/common/MermaidFixButton.tsx (hunk 12 above)
Comment (chrarnoldus) [reply webview-ui/src/components/common/MermaidFixButton.tsx:2]: you could also put it in a kilocode folder, but I guess that will make merging back harder.

**Review by chrarnoldus — APPROVED** [review]

File: webview-ui/src/services/mermaidSyntaxFixer.ts (hunk 13 above)
Comment (markijbema) [reply webview-ui/src/services/mermaidSyntaxFixer.ts:2]: ok daar gaat ergens iets mis met dubbele escapes, ik doe t even met de hand

**Comment by HadesArchitect** [comment]
Mark, thank you so much for the screenshot!
