### PR TITLE
fix dropdown bug

### LINKED ISSUE #465: Multiple Scrollbars
### Add a description (be as detailed as possible)

Image

Windsurf Version: 1.9.1
Windsurf Extension Version: 1.46.2
Windsurf Commit: 30ecb9e3eef98030919c495b29458a36a0b5b2d1
VSCode OSS Version: 1.99.1
Commit: 30ecb9e3eef98030919c495b29458a36a0b5b2d1
Date: 2025-05-20T02:24:57.232Z
Electron: 34.3.2
ElectronBuildId: undefined
Chromium: 132.0.6834.210
Node.js: 20.18.3
V8: 13.2.152.41-electron.0
OS: Darwin arm64 24.3.0

### PR DESCRIPTION
**Pull request by tru-kilo**
## Context

Fixes https://github.com/Kilo-Org/kilocode/issues/465

-->

## Screenshots

**Before**
Screenshot 2025-05-28 at 6 01 24 PM

**After**
Screenshot 2025-05-28 at 6 04 30 PM

### CODE REVIEW

File: webview-ui/src/components/ui/select-dropdown.tsx [hunk 1]
```diff
@@ -217,103 +217,93 @@ export const SelectDropdown = React.memo(
...
-										<X
-											className="text-vscode-input-foreground opacity-50 hover:opacity-100 size-4 p-0.5 cursor-pointer"
-											onClick={onClearSearch}
-										/>
-									</div>
-								)}
-							</div>
-
-							{/* Dropdown items - Use windowing for large lists */}
-							<div className="max-h-[300px] overflow-y-auto">
```
Comment (kevinvandijk) [inline webview-ui/src/components/ui/select-dropdown.tsx:243]: Just a gut feeling, didn't try it but would removing only the `overflow-y-auto` class here solve not the issue as well, without the need for all the other changes being done?

**Review by kevinvandijk — CHANGES_REQUESTED** [review]
Feels like a lot of changes to fix a simple thing? Can you try my suggestion on the original code? The less changes the better considering we want to stay compatible with upstream

File: webview-ui/src/components/ui/select-dropdown.tsx (hunk 1 above)
Comment (tru-kilo) [reply webview-ui/src/components/ui/select-dropdown.tsx:243]: it doesn't work, unless you want the search bar to also scroll within the container? I'll try and clean it up, it wasn't a lot of changes but the diff makes it look like it is, I just had to remove a wrapped div

Comment (kevinvandijk) [reply webview-ui/src/components/ui/select-dropdown.tsx:243]: Ah ok, clear! The div looked huge but makes sense then indeed! Can you drop a comment somewhere near it with a kilocode_change marker that says that it was removed intentionally?

**Review by kevinvandijk — APPROVED** [review]
Don't forget to add a changeset :)

File: webview-ui/src/components/ui/select-dropdown.tsx (hunk 1 above)
Comment (janpaul123) [reply webview-ui/src/components/ui/select-dropdown.tsx:243]: When looking at it with whitespace ignored the diff doesn't look so big anymore :) In fact most of the changes below come from the reduced indentation causing Prettier to put things on the same line.

Screenshot 2025-06-03 at 09 54 34

File: webview-ui/src/components/ui/select-dropdown.tsx [hunk 2]
```diff
@@ -217,103 +217,96 @@ export const SelectDropdown = React.memo(
...
-								{groupedOptions.length === 0 && searchValue ? (
-									<div className="py-2 px-3 text-sm text-vscode-foreground/70">No results found</div>
-								) : (
-									<div className="py-1">
-										{groupedOptions.map((option, index) => {
-											// Memoize rendering of each item type for better performance
```
Comment (janpaul123) [inline webview-ui/src/components/ui/select-dropdown.tsx:249]: Unnecessarily removed comment

File: webview-ui/src/components/ui/select-dropdown.tsx [hunk 3]
```diff
@@ -217,103 +217,96 @@ export const SelectDropdown = React.memo(
...
-												return (
-													<div
-														key={`label-${index}`}
-														className="px-3 py-1.5 text-sm opacity-50">
-														{option.label}
-													</div>
-												)
-											}
-
-											// Use stable keys for better reconciliation
```
Comment (janpaul123) [inline webview-ui/src/components/ui/select-dropdown.tsx:273]: Unnecessarily removed comment

File: webview-ui/src/components/ui/select-dropdown.tsx (hunk 1 above)
Comment (EamonNerbonne) [reply webview-ui/src/components/ui/select-dropdown.tsx:243]: prettier loves 🧌 -ing diffs, alas.
