### PR TITLE
Native JSON MCP Tool Calling

### LINKED ISSUE #3229: Model fails to call the mcp server correctly (Matt PR about native mcp server calls)
### Plugin Type

VSCode Extension

### App Version

a PR from Matt v4.109.1-alpha

### Description

Some models fails to use the native mcp server calls
this for example is GPT5-codex medium using kilocode provider

Image 

### Reproduction steps

1. Create any file (in my case it was a single livewire file)
2. prompt: read this file @/app/Livewire/Counter.php and use context7 to get the latest livewire 3.x docs
3. wait for the output

### Provider

KiloCode

### Model

GPT5-Codex medium

### System Information

_No response_

### PR DESCRIPTION
**Pull request by mcowger**
Implement dynamic MCP native tool generation support.

Available MCP servers are enumerated for their published tools, and dynamic tool definitions are generated
in the form of use_mcp_tool___servername___toolname.   

## Implementation

- Add helper functions to detect and parse dynamic MCP tool names
- Normalize dynamic tools to standard `use_mcp_tool` format
- Use triple underscores (___) as separator to allow underscores in tool names
- Extract toolInputProps and convert to JSON string for MCP server compatibility
- Renames properties called `type` to `renamed_type` internally before sending to model, because `type` is a reserved word for many parsers.
- Update tool name generation in mcp_server.ts
- Adjust tool definitions to align to OpenAI and Anthropic requirements

### CODE REVIEW

File: src/core/prompts/tools/native-tools/ask_followup_question.ts [hunk 1]
```diff
@@ -15,9 +15,9 @@ export default {
 					description: "Clear, specific question that captures the missing information you need",
 				},
 				follow_up: {
-					type: ["array", "null"],
+					type: "array",
 					description:
-						"Optional list of 2-4 suggested responses; each suggestion must be a complete, actionable answer and may include a mode switch",
+						"Required list of 2-4 suggested responses; each suggestion must be a complete, actionable answer and may include a mode switch",
```
Comment (chrarnoldus) [inline src/core/prompts/tools/native-tools/ask_followup_question.ts:20]: This doesn't match the XML description

Comment (mcowger) [reply src/core/prompts/tools/native-tools/ask_followup_question.ts:20]: It doesn't and thats intentional.  Asking a question without offering responses suggestions seems like an error, and I believe is part of the cause of some of the Promise rejections.

**Comment by mcowger** [comment]
This is starting to get a bit stale.  

IMO this is the last requirement to mark JSON calls as "beta " vs purely experimental.

**Review by chrarnoldus — APPROVED** [review]
