### PR TITLE
JetBrains Plugin - Performance and Stability Improvements

### LINKED ISSUE #4874: JetBrains Plugin: Kilocode floods terminal log until opened
### Plugin Type

JetBrains Plugin

### App Version

4.143.2

### Description

When you open JetBrain via CLI you can see flood of never ending WARN messages
`WARN - #ai.kilocode.jetbrains.webview.WebViewInstance - JCEF browser not fully initialized (URL is null/empty), deferring JavaScript execution
`
until you open the KiloCode plugin 

Image

### Reproduction steps

Open terminal
Via terminal run PhpStorm
See that the terminal is being flooded with WARN
Open KiloCode plugin - WARN is stopped

### Provider

_No response_

### Model

_No response_

### System Information

_No response_

### PR DESCRIPTION
**Pull request by catrielmuller**
## Context

-  Fix #4912 
-  Fix #5081 
-  Fix #4874

This PR addresses critical performance and stability issues in the JetBrains plugin, specifically targeting webview flickering and thread management problems that were causing UI freezes and resource leaks. The changes implement a comprehensive solution across multiple phases to prevent thread leaks, improve UI responsiveness, and enhance overall plugin stability.

The main issues addressed:

- Webview flickering during rendering causing poor user experience
- Thread leaks from improper coroutine scope management
- UI freezes due to blocking operations on the EDT (Event Dispatch Thread)
- Resource leaks from undisposed monitoring infrastructure
- Race conditions in concurrent scope operations

### Phase 1: Core Thread Management Improvements

**WebViewInstance.kt**

- Replaced `Timer` with IntelliJ's `Alarm` API for better thread management and automatic cleanup
- Implemented proper coroutine scope lifecycle with `SupervisorJob` for fault isolation
- Added bounded thread pool (`boundedIODispatcher`) to prevent thread explosion
- Moved EDT operations outside synchronized blocks to prevent deadlocks
- Added proper disposal of coroutine scopes and thread pools in `dispose()`

**Key changes:**

- Synchronized blocks now only handle flag checks, not callback execution
- Page load callbacks execute on EDT using `invokeLater` to avoid blocking
- JavaScript execution retries use `Alarm` instead of `Timer` for proper lifecycle management
- Scope registry integration for monitoring active coroutine scopes

### Phase 2: Monitoring Infrastructure

**New monitoring classes:**

- [`ScopeRegistry.kt`](jetbrains/plugin/src/main/kotlin/ai/kilocode/jetbrains/monitoring/ScopeRegistry.kt) - Tracks active coroutine scopes and their lifecycle
- [`ThreadMonitor.kt`](jetbrains/plugin/src/main/kotlin/ai/kilocode/jetbrains/monitoring/ThreadMonitor.kt) - Monitors thread count and detects potential leaks
- [`DisposableTracker.kt`](jetbrains/plugin/src/main/kotlin/ai/kilocode/jetbrains/monitoring/DisposableTracker.kt) - Tracks disposable resources for leak detection

These tools provide visibility into resource usage and help identify leaks during development and testing.

### Phase 3: Configuration and Tuning

**PerformanceSettings.kt**

- Added configurable debounce settings for file events, editor activation, and editor edits
- Configurable RPC concurrency limits to prevent overwhelming the system
- Default values balanced for responsiveness and resource usage

### Phase 4: VSCode DOM Patches

**deps/patches/vscode/jetbrains.patch**

- Updated VSCode DOM implementation to fix webview rendering issues
- Improved event handling to prevent flickering
- Better synchronization between webview state and UI updates

### Phase 5: Build System Integration

**package.json & turbo.json**

- Added `jetbrains-host:build` task for building the JetBrains host component
- Proper dependency management in Turbo configuration

### Testing

Comprehensive test coverage added:

- [`PerformanceSettingsTest.kt`](jetbrains/plugin/src/test/kotlin/ai/kilocode/jetbrains/config/PerformanceSettingsTest.kt) - Validates configuration values
- [`ThreadLeakPreventionTest.kt`](jetbrains/plugin/src/test/kotlin/ai/kilocode/jetbrains/integration/ThreadLeakPreventionTest.kt) - Integration tests for thread leak prevention
- [`ScopeRegistryTest.kt`](jetbrains/plugin/src/test/kotlin/ai/kilocode/jetbrains/monitoring/ScopeRegistryTest.kt) - Tests scope lifecycle tracking
- [`ThreadMonitorTest.kt`](jetbrains/plugin/src/test/kotlin/ai/kilocode/jetbrains/monitoring/ThreadMonitorTest.kt) - Tests thread monitoring functionality
- [`DisposableTrackerTest.kt`](jetbrains/plugin/src/test/kotlin/ai/kilocode/jetbrains/monitoring/DisposableTrackerTest.kt) - Tests resource tracking

### Tradeoffs

- **Memory vs Thread Count**: Bounded thread pools use slightly more memory but prevent unbounded thread growth
- **Responsiveness vs Resource Usage**: Debounce settings balance UI responsiveness with system load
- **Monitoring Overhead**: Monitoring infrastructure adds minimal overhead but provides valuable debugging information

### Testing Webview Stability

1. Open a JetBrains IDE with the Kilo Code plugin installed
2. Open the Kilo Code chat panel (webview)
3. Interact with the chat interface (send messages, scroll, resize)
4. **Expected**: No flickering or visual artifacts during rendering
5. **Expected**: Smooth UI updates without freezes

### Testing Thread Leak Prevention

1. Enable thread monitoring by setting log level to DEBUG
2. Open and close the Kilo Code panel multiple times (20+ iterations)
3. Monitor thread count in IDE logs or using a profiler
4. **Expected**: Thread count should stabilize and not grow unbounded
5. **Expected**: No "thread leak detected" warnings in logs

### Testing Resource Cleanup

1. Open the Kilo Code panel
2. Perform various operations (file edits, command execution, etc.)
3. Close the panel
4. Check IDE logs for disposal messages
5. **Expected**: All resources properly disposed (check for "WebView instance released" messages)
6. **Expected**: No resource leak warnings

### Testing Under Load

1. Open multiple project windows with Kilo Code enabled
2. Perform rapid operations in each window (file edits, panel toggles)
3. Monitor system resources (CPU, memory, thread count)
4. **Expected**: System remains responsive
5. **Expected**: Thread count stays within reasonable bounds (< 100 growth)
6. **Expected**: No UI freezes or deadlocks

### Running Tests

```bash
# Run all JetBrains plugin tests
cd jetbrains/plugin
./gradlew test

# Run specific test suites
./gradlew test --tests "ThreadLeakPreventionTest"
./gradlew test --tests "PerformanceSettingsTest"
```

### Monitoring During Development

Enable debug logging to see monitoring output:

```kotlin
// In your IDE's log settings, set these to DEBUG level:
ai.kilocode.jetbrains.monitoring
ai.kilocode.jetbrains.webview
```

This will show:

- Thread count changes
- Scope lifecycle events
- Resource allocation/disposal
- Performance metrics

### CODE REVIEW

File: jetbrains/plugin/src/main/kotlin/ai/kilocode/jetbrains/core/ExtensionSocketServer.kt [hunk 1]
```diff
@@ -1,9 +1,6 @@
-// SPDX-FileCopyrightText: 2025 Weibo, Inc.
-//
-// SPDX-License-Identifier: Apache-2.0
```
Comment (markijbema) [inline jetbrains/plugin/src/main/kotlin/ai/kilocode/jetbrains/core/ExtensionSocketServer.kt:3]: I don't know why this was here, removing it is no issue?

File: jetbrains/plugin/src/main/kotlin/ai/kilocode/jetbrains/webview/WebViewManager.kt [hunk 2]
```diff
@@ -749,55 +877,65 @@ class WebViewInstance(
...
                     val injectThemeScript = """
                         (function() {
-                            // Check if already injected at the top level
-                            if (window.__cssVariablesInjected) {
-                                console.log("CSS variables already injected, skipping");
-                                return;
+                            // Version tracking for theme injection
+                            const THEME_VERSION = Date.now();
+                            
+                            // Enhanced idempotency check - prevent injection if less than 100ms has passed
```
Comment (markijbema) [inline jetbrains/plugin/src/main/kotlin/ai/kilocode/jetbrains/webview/WebViewManager.kt:883]: any reason why those cant change within 100ms? Feels a bit random, cant we do actual idempotency somehow?

**Review by markijbema — APPROVED** [review]
It seems sensible, but concurrency stuff is hard to review for correctness; but I assumed you've tested this well enough.

I've asked some questions, but feel free to merge

File: jetbrains/plugin/src/main/kotlin/ai/kilocode/jetbrains/core/ExtensionSocketServer.kt (hunk 1 above)
Comment (catrielmuller) [reply jetbrains/plugin/src/main/kotlin/ai/kilocode/jetbrains/core/ExtensionSocketServer.kt:3]: I've been removing headers from the files we've modified because LLM models tend to add this header to new files as well.

File: jetbrains/plugin/src/main/kotlin/ai/kilocode/jetbrains/webview/WebViewManager.kt (hunk 2 above)
Comment (catrielmuller) [reply jetbrains/plugin/src/main/kotlin/ai/kilocode/jetbrains/webview/WebViewManager.kt:883]: This is to prevent flickering when the plugin browser windows it's out of focus.
