### PR TITLE
Fix confirm dialog in settings view

### LINKED ISSUE #217: Cannot close settings menu
### Which version of the app are you using?

main branch

### Which API Provider are you using?

Kilo Code

### Which Model are you using?

na

### What happened?

https://github.com/user-attachments/assets/86610b40-12c7-45a7-b27b-928d0b95a3f8

clicking the settings menu, not even changing anything gets you stuck in the settings menu.

### Steps to reproduce

1. click settings button
2. try to exit settings

### Relevant API REQUEST output

```shell

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kevinvandijk**
This is not an ideal fix but since we have plans for our own redesigned settings view anyway I think this sufficient for now

- Resolves #217

### CODE REVIEW

File: webview-ui/src/components/settings/SettingsView.tsx [hunk 1]
```diff
@@ -299,11 +309,26 @@ const SettingsView = forwardRef<SettingsViewRef, SettingsViewProps>(({ onDone, o
...
+	)
+
+	// Call the stored callback after discarding is complete
+	useEffect(() => {
+		if (discardInProgress === true) {
 			confirmDialogHandler.current?.()
+			setDiscardInProgress(false)
 		}
-	}, [])
+	}, [discardInProgress])
```
Comment (janpaul123) [inline webview-ui/src/components/settings/SettingsView.tsx]: This whole structure feels a bit weird. If you need to do something after other callbacks are completed, why not just a `setTimeout(() => confirmDialogHandler.current?.(), 0)`? in the place of `setDiscardInProgress(true)`?

Comment (kevinvandijk) [reply webview-ui/src/components/settings/SettingsView.tsx]: Threw myself in a bit of a React anti-pattern here. My thinking was that I want to wait for a re-render to happen but you're right, a `setTimeout` works here as well. Changed it!

**Review by janpaul123 — APPROVED** [review]
🎉

File: webview-ui/src/components/settings/SettingsView.tsx [hunk 2]
```diff
@@ -98,16 +98,25 @@ const SettingsView = forwardRef<SettingsViewRef, SettingsViewProps>(({ onDone, o
 	const [isChangeDetected, setChangeDetected] = useState(false)
 	const [errorMessage, setErrorMessage] = useState<string | undefined>(undefined)
 
+	const prevApiConfigName = useRef(currentApiConfigName)
+	const confirmDialogHandler = useRef<() => void>()
+
+	const [cachedState, setCachedState] = useState(extensionState)
+
 	// kilocode_change begin
```
Comment (EamonNerbonne) [inline webview-ui/src/components/settings/SettingsView.tsx:106]: presumably this lines should go up

Comment (EamonNerbonne) [reply webview-ui/src/components/settings/SettingsView.tsx:106]: ah, no, those line are there  on line 107 in the old code too...
