### PR TITLE
fix(vscode): fix hanging sessions for permissions bug

### LINKED ISSUE #9283: Session hang in one session
### Description

Context:
* Multiple sessions in agent manager running. Permissions prompts appearing in both.
* One of the sessions hung, being unable to respond to the tool call, the buttons show as disabled.

* Session export: https://drive.google.com/file/d/1kURDrVNftuJLBBIpyQjRbVQ4teb8PLao/view?usp=sharing
* Heap hump (~900MB): https://drive.google.com/file/d/1WYbmMfNO0wg3Fnwr_EM4upgI4duOZC73/view?usp=sharing

Image

### Plugins

_No response_

### Kilo version

_No response_

### Steps to reproduce

_No response_

### Screenshot and/or share link

_No response_

### Operating System

_No response_

### Terminal

_No response_

### PR DESCRIPTION
**Pull request by alex-alecu**
## Why

Fixes https://github.com/Kilo-Org/kilocode/issues/9283

Sometimes a permission pop-up stayed on screen after it was already answered somewhere else. That left broken buttons behind and could also make settings save fail for no good reason.

## What changed

Permission replies now go back to the workspace that asked for them, even if the session came from another panel or worktree. If the app learns that a prompt was already handled, it clears the old prompt instead of leaving a dead button on screen. The server now says when a permission is gone, and the client uses that to refresh cleanly. This also keeps the same stale case from breaking settings saves and makes the behavior match in both permission paths.

## How to test

1. Open the same repo in two VS Code windows or worktrees and trigger a permission prompt.
2. Answer it in one place, then try the old copy in the other place.
3. Confirm the old prompt disappears instead of hanging or leaving dead buttons.
4. Change a setting after that and confirm the save still works.

### CODE REVIEW

File: packages/kilo-vscode/src/KiloProvider.ts [hunk 1]
```diff
@@ -2894,6 +2902,16 @@ export class KiloProvider implements vscode.WebviewViewProvider, TelemetryProper
...
     if (isEventFromForeignProject(event, this.projectID)) return
 
+    // Record per-permission directory from the SSE envelope so replies route
+    // to the Instance that actually owns the pending entry. Clean up on reply
+    // so the map doesn't grow without bound.
+    if (event.type === "permission.asked" && directory) {
+      this.permissionDirectories.set(event.properties.id, directory)
+    }
+    if (event.type === "permission.replied") {
+      this.permissionDirectories.delete(event.properties.requestID)
```
[the remark this answers is not in the document]
Comment (alex-alecu) [reply packages/kilo-vscode/src/KiloProvider.ts:2978]: Fixed in 167a6d2e2bc. `fetchAndSendPendingPermissions` now prunes entries from the map that are no longer pending on any backend.

**Comment by alex-alecu** [comment]
Additional manual test passed with `gpt-4o-mini`.

Tested:
- Ran the local worktree backend with `openrouter/openai/gpt-4o-mini` and a real OpenRouter request.
- Prompted the model to use the bash tool so the backend produced a real permission prompt.
- Sent a permission reply to the wrong workspace directory, then replied through the owning workspace directory.
- Replied to the already-answered permission and saved always-rules for the already-answered permission.
- Updated global config after the stale permission paths.

Verified:
- Misrouted permission reply returned 404 and the owning workspace permission stayed pending.
- Correct permission reply returned 200, cleared the pending prompt, and the real-model tool call completed.
- Stale `reply` and `always-rules` requests returned 404.
- SSE `permission.asked` and `permission.replied` events included the source workspace directory.
- SQLite persisted the session and completed tool part, and the config file persisted the later settings update.

**Comment by alex-alecu** [comment]
Manual test passed.

Tested:
- Started the local branch backend with `bun dev serve` and drove it over HTTP/SSE using a real OpenRouter model to trigger bash permission prompts.
- Verified a wrong-directory permission reply returns 404 and leaves the original directory's pending permission intact.
- Verified the correct-directory reply succeeds, clears the pending permission, and a second/stale reply returns 404.
- Verified `always-rules` succeeds for a live prompt, persists an allow rule, and returns 404 after the permission is already answered.
- Verified a settings-drain-style reject clears a live prompt, and a stale follow-up reject returns 404.

Verified:
- Global SSE permission events include the owning directory envelope for both `permission.asked` and `permission.replied`.
- Pending permission state is isolated per directory and clears after accepted replies/rejects.
- Persisted config contains the saved bash allow rule from `always-rules`.

File: packages/kilo-vscode/src/kilo-provider/handlers/permission-handler.ts [hunk 2]
```diff
@@ -16,6 +16,18 @@ export interface PermissionContext {
   readonly sessionDirectories: ReadonlyMap<string, string>
   postMessage(msg: unknown): void
   getWorkspaceDirectory(sessionId?: string): string
+  /**
+   * Record the SSE envelope directory for a pending permission. Used so that
+   * replies land in the Instance that actually holds the pending entry,
```
Comment (imanolmzd-svg) [inline packages/kilo-vscode/src/kilo-provider/handlers/permission-handler.ts]: Plenty of comments throughout the PR - Please reduce them and try to make the code self-documenting

**Review by imanolmzd-svg — CHANGES_REQUESTED** [review]

File: packages/kilo-vscode/src/kilo-provider/handlers/permission-handler.ts (hunk 2 above)
Comment (alex-alecu) [reply packages/kilo-vscode/src/kilo-provider/handlers/permission-handler.ts]: Done in c05d382.

**Review by imanolmzd-svg — APPROVED** [review]
