### PR TITLE
fix: CLI file duplication bug when writing files (#5318)

### LINKED ISSUE #5318: Kilocode CLI write to file twice
### Plugin Type

Kilo Code CLI

### App Version

0.20.0

### Description

When working with files. Agent create new file (one) and write content to file twice. It's visible in logs

### Reproduction steps

1. Save any text file? example: html code with form tag
2. Tell agent extract form and javascript and save it to another file
3. See content of new saved file

### Provider

_No response_

### Model

_No response_

### System Information

_No response_

### PR DESCRIPTION
**Pull request by marius-kilocode**
## Summary

Fixes #5318 - CLI writes file content twice when creating or editing files.

## Problem

When the Kilo Code CLI creates or edits files, the content was being duplicated at the end of the file. This was visible in logs and caused issues where:
- New files had their content written twice
- When the LLM tried to fix the duplication, it added the code again, creating 3+ copies

### 1. Multi-line Edit Logic in `applyEdit` (Primary)

In `packages/agent-runtime/src/host/VSCode.ts`, the line-based edit logic had a bug:

```typescript
const lastLine = lines[endLine] || ""
const newContent = firstLine.substring(0, startChar) + textEdit.newText + lastLine.substring(endChar)
```

When `endChar = 0`, `lastLine.substring(0)` returns the **entire** last line, causing duplication.

### 2. Multiple `applyEdit` Calls in CLI Mode (Secondary)

In `src/integrations/editor/DiffViewProvider.ts`, the `update()` method made up to 3 `applyEdit` calls when finalizing. In CLI mode, each call writes to disk, causing race conditions and potential duplication.

### VSCode.ts Changes
- Replaced line-based editing with offset-based editing using `slice()` operations
- Added `[...edits]` spread to prevent mutation of the original edit array

### DiffViewProvider.ts Changes
- Added CLI-specific code path that makes a **single** `applyEdit` call to replace the entire document content
- This eliminates the multiple-write issue in CLI mode

## Testing

- Added new test file `packages/agent-runtime/src/host/__tests__/VSCode.applyEdit.spec.ts`
- Added CLI mode test in `src/integrations/editor/__tests__/DiffViewProvider.spec.ts`

### CODE REVIEW

File: packages/agent-runtime/src/host/VSCode.ts [hunk 1]
```diff
@@ -1506,36 +1506,32 @@ export class WorkspaceAPI {
 					// File doesn't exist, start with empty content
 				}
 
+				const originalLines = content.split("\n")
```
Comment (chrarnoldus) [inline packages/agent-runtime/src/host/VSCode.ts:1509]: does this hardcoded newline character work as intended on window?

**Review by chrarnoldus — APPROVED** [review]
