### PR TITLE
fix: migrate default project folder from .opencode to .kilo

### LINKED ISSUE #6370: Plan files in ask mode are saved in a opencode directory
### Description

When in Ask mode plan files are visibly saved in a `./opencode` directory.

### Plugins

_No response_

### Kilo version

_No response_

### Steps to reproduce

Make a plan in Ask mode. Look at where the file is written.

### Screenshot and/or share link

Image

### Operating System

_No response_

### Terminal

_No response_

### PR DESCRIPTION
**Pull request by catrielmuller**
## Context

Kilo should use `.kilo` as its default project folder everywhere. Several places in the codebase still referenced `.opencode` as the default write destination or only looked up `.opencode` when discovering directories. This change makes `.kilo` the primary folder and keeps `.opencode` as a read-only fallback for backward compatibility.

Fixes #6370 — plan files were being written to `.opencode/plans/` instead of `.kilo/plans/`.

## Implementation

The changes follow a clear principle:
- **Write operations** → always use `.kilo`
- **Read/discovery operations** → check `.kilo` first, fall back to `.opencode`
- **Detection/cleanup** → recognize both
- **User-facing display strings** → reference `.kilo` only

### Files changed

| File | Change |
|------|--------|
| `src/session/index.ts` | Plan write path → `.kilo/plans/` |
| `src/agent/agent.ts` | Plan agent edit permission: primary `.kilo/plans/*.md`, fallback `.opencode/plans/*.md` |
| `src/cli/cmd/agent.ts` | Agent creation write target → `.kilo/agent/` |
| `src/kilocode/components/tips.tsx` | User-facing tip strings updated to reference `.kilo/*` subdirs; added missing tips for config, permissions, tools, plugins, themes |
| `src/cli/cmd/tui/context/theme.tsx` | Theme discovery targets `[".kilo", ".opencode"]` (was only `.opencode`) |
| `src/cli/cmd/mcp.ts` | Config path resolution checks `.kilo/kilo.json` first; default write path is `kilo.json` |
| `src/installation/index.ts` | Curl install detection recognizes both `.kilo/bin` and `.opencode/bin` |
| `src/file/ripgrep.ts` | File tree builder skips both `.kilo` and `.opencode` dirs |

Already-correct files (no changes needed): `config/paths.ts`, `config/config.ts`, `config/tui.ts`, `cli/cmd/uninstall.ts` — these already implement the `.kilo`-first / `.opencode`-fallback pattern.

### Tests

- `test/agent/agent.test.ts` — plan permission test verifies both `.kilo/plans/` and `.opencode/plans/` are allowed; skill dir test uses `.kilo/skill/`
- `test/kilocode/plan-exit-detection.test.ts` — mock output updated to `.kilo/plans/plan.md`
- `test/skill/skill.test.ts` — primary skill directory tests use `.kilo/skill/`; `.opencode/skill/` kept in backward-compat test only
- `test/file/ripgrep.test.ts` — new test verifying `.kilo` dirs are excluded from `tree()` output

## Screenshots

| before | after |
| ------ | ----- |
| Plan files saved to `.opencode/plans/...` | Plan files saved to `.kilo/plans/...` |

## How to Test

1. Open a project with a git repo
2. Switch to Plan agent (or use Ask mode with plan generation)
3. Ask the agent to create a plan
4. When `plan_exit` is called, verify the output says `Plan is ready at .kilo/plans/...`
5. Verify the `.kilo/plans/` directory is created in the project root (not `.opencode/plans/`)

For backward compat:
- Create a plan in `.opencode/plans/` manually, run the plan agent — it should still be able to edit files under `.opencode/plans/`

## Get in Touch

Discord: catrielmuller

### CODE REVIEW

File: packages/opencode/src/agent/agent.ts [hunk 1]
```diff
@@ -110,7 +110,8 @@ export namespace Agent {
             },
             edit: {
               "*": "deny",
-              [path.join(".opencode", "plans", "*.md")]: "allow",
+              [path.join(".kilo", "plans", "*.md")]: "allow", // kilocode_change
```
Comment (markijbema) [inline packages/opencode/src/agent/agent.ts:113]: shouldnt it be kilocode? or are we deprecating that? because old extension users will still have data there right?

**Review by markijbema — APPROVED** [review]

File: packages/opencode/src/agent/agent.ts (hunk 1 above)
Comment (catrielmuller) [reply packages/opencode/src/agent/agent.ts:113]: We moved everyhting to `.kilo`
