### PR TITLE
fix(settings): correct Thinking Budget value parsing and boundary handling.

### LINKED ISSUE #1257: Max thinking tokens can be set to a value that's too large
### Description

https://discord.com/channels/1349288496988160052/1393171027143561318

### PR DESCRIPTION
**Pull request by tejaschokhawala**
## Context

Fixes #1257: Clamp Thinking Budget to a safe upper bound to address cases where users could set an excessively large value.

## Implementation

- Introduced a max cap constant in [webview-ui/src/components/settings/ThinkingBudget.tsx:0].
- Applied clamping so the persisted value never exceeds the defined max (no new UI messages or helper text changes).

## Screenshots

| before | after |
| ------ | ----- |
| Value could exceed practical limits | Input is capped at the defined maximum |

## How to Test

- Open the Thinking Budget setting.
- Claude Opus 4: Maximum output of 32,000 tokens (including thinking tokens)
- Claude Sonnet 4: Maximum output of 64,000 tokens (including thinking tokens)
- Confirm the stored/displayed value is clamped to the max cap and does not exceed it.

### CODE REVIEW

File: webview-ui/src/components/settings/ThinkingBudget.tsx [hunk 1]
```diff
@@ -41,6 +41,14 @@ export const ThinkingBudget = ({ apiConfiguration, setApiConfigurationField, mod
 		}
 	}, [isReasoningBudgetSupported, customMaxThinkingTokens, modelMaxThinkingTokens, setApiConfigurationField])
 
+	// If the custom max output tokens are going to exceed it's limit due
+	// to the model info max tokens then we need to shrink it appropriately.
+	useEffect(() => {
+		if (isReasoningBudgetSupported && modelInfo?.maxTokens && customMaxOutputTokens > modelInfo.maxTokens) {
+			setApiConfigurationField("modelMaxTokens", modelInfo.maxTokens || DEFAULT_HYBRID_REASONING_MODEL_MAX_TOKENS)
+		}
+	}, [isReasoningBudgetSupported, customMaxOutputTokens, modelInfo?.maxTokens, setApiConfigurationField])
```
Comment (chrarnoldus) [inline webview-ui/src/components/settings/ThinkingBudget.tsx:51]:
```suggestion
	// kilocode_change start
	// If the custom max output tokens are going to exceed it's limit due
	// to the model info max tokens then we need to shrink it appropriately.
	useEffect(() => {
		if (isReasoningBudgetSupported && modelInfo?.maxTokens && customMaxOutputTokens > modelInfo.maxTokens) {
			setApiConfigurationField("modelMaxTokens", modelInfo.maxTokens || DEFAULT_HYBRID_REASONING_MODEL_MAX_TOKENS)
		}
	}, [isReasoningBudgetSupported, customMaxOutputTokens, modelInfo?.maxTokens, setApiConfigurationField])
	// kilocode_change end
```

**Review by chrarnoldus — APPROVED** [review]
