### PR TITLE
Fix checkpoints do not always include a revert option

### LINKED ISSUE #366: Checkpoints do not always include a revert option
Checkpoints do not always include a revert option.  Checkpoint reverts are periodically available, thus when you need to revert, you must go back to the begin of a session, or even a previous session.

Image

### PR DESCRIPTION
**Pull request by catrielmuller**
## Context

Resolve #366 

The shadow git it's computing the isFirst in base of the current checkpoint array, this produce some side effect that happen when you modify the git history stoping and re inti the cline task.
This value it's only used on the frontend so I made this simple fix to don't involve a refactor on the core making the fix retro compatible.
The final fix should remove the `isFirst` attribute on all checkpoint types and use this logic on the frontend to get that.

## Implementation

This PR ensures the isFirst flag is always present on checkpoint data (for backwards compatibility) by computing it on the frontend based on from and to values, restoring the revert option for legacy checkpoints.

- Replaces direct result.data return with an object that spreads result.data and adds isFirst
- Computes isFirst as result.data.from === result.data.to
- Includes temporary kilocode_change comment markers around the new logic

### Before
image

### After
image

## How to Test

- You need modify the git history restoring the task to any point and continue making prompts to made checkpoints

### CODE REVIEW

File: webview-ui/src/components/chat/checkpoints/CheckpointSaved.tsx [hunk 1]
```diff
@@ -26,7 +26,12 @@ export const CheckpointSaved = ({ checkpoint, ...props }: CheckpointSavedProps)
 			return undefined
 		}
 
-		return result.data
+		// kilocode_change start
```
Comment (hassoncs) [inline webview-ui/src/components/chat/checkpoints/CheckpointSaved.tsx:29]: Maybe include a comment here explaining this fix so the next person is less* confused as so why we are recalculating isFirst here?

**Review by hassoncs — APPROVED** [review]
Looks good! Please add a little comment near your fix as an explanation for the next person, but overall makes sense to me!

**Review by chrarnoldus — APPROVED** [review]
