### PR TITLE
CLI - Refactor types

### LINKED ISSUE #3493: CLI - Enforce no-explicit-any
Fix the untyped definitions, import the types from the extension when is possible.

## Logs
```
/Users/catrielmuller/Dev/Kilo-Org/kilocode/cli/src/__tests__/config-command.test.ts
  14:36  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  14:52  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

/Users/catrielmuller/Dev/Kilo-Org/kilocode/cli/src/__tests__/config-default-creation.test.ts
  23:36  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  23:52  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

/Users/catrielmuller/Dev/Kilo-Org/kilocode/cli/src/__tests__/history.test.ts
   5:55  warning  'vi' is defined but never used. Allowed unused vars must match /^_/u              @typescript-eslint/no-unused-vars
  37:12  warning  'error' is defined but never used. Allowed unused caught errors must match /^_/u  @typescript-eslint/no-unused-vars

/Users/catrielmuller/Dev/Kilo-Org/kilocode/cli/src/commands/__tests__/clear.test.ts
   5:44  warning  'afterEach' is defined but never used. Allowed unused vars must match /^_/u  @typescript-eslint/no-unused-vars
  75:64  warning  Unexpected any. Specify a different type                                     @typescript-eslint/no-explicit-any

/Users/catrielmuller/Dev/Kilo-Org/kilocode/cli/src/commands/__tests__/model.autocomplete.test.ts
  11:26  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

/Users/catrielmuller/Dev/Kilo-Org/kilocode/cli/src/commands/__tests__/new.test.ts
   75:61  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  142:61  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

/Users/catrielmuller/Dev/Kilo-Org/kilocode/cli/src/commands/__tests__/profile.test.ts
  144:65  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  176:65  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  213:65  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  242:12  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

/Users/catrielmuller/Dev/Kilo-Org/kilocode/cli/src/commands/__tests__/teams.test.ts
  217:65  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  250:65  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  283:65  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  316:65  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  340:12  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  375:12  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

/Users/catrielmuller/Dev/Kilo-Org/kilocode/cli/src/commands/core/parser.ts
   40:32  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  134:37  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

/Users/catrielmuller/Dev/Kilo-Org/kilocode/cli/src/commands/core/types.ts
   28:12  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   34:26  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   35:25  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   36:24  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   38:30  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   65:26  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   94:33  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  103:27  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

/Users/catrielmuller/Dev/Kilo-Org/kilocode/cli/src/commands/model.ts
   19:44  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   77:42  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  152:39  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  251:37  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  319:36  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  357:25  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

/Users/catrielmuller/Dev/Kilo-Org/kilocode/cli/src/commands/profile.ts
  11:37  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

/Users/catrielmuller/Dev/Kilo-Org/kilocode/cli/src/commands/teams.ts
   25:35  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   98:36  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  201:85  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

/Users/catrielmuller/Dev/Kilo-Org/kilocode/cli/src/communication/ipc.ts
    8:8   warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   38:20  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   38:31  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   66:35  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   84:14  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  204:61  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

/Users/catrielmuller/Dev/Kilo-Org/kilocode/cli/src/config/__tests__/persistence-merge.test.ts
  13:36  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  13:52  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

/Users/catrielmuller/Dev/Kilo-Org/kilocode/cli/src/config/__tests__/persistence.test.ts
  31:36  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  31:52  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

/Users/catrielmuller/Dev/Kilo-Org/kilocode/cli/src/config/types.ts
  112:17  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

/Users/catrielmuller/Dev/Kilo-Org/kilocode/cli/src/config/validation.ts
  79:4  warning  Unexpected lexical declaration in case block  no-case-declarations
  80:4  warning  Unexpected lexical declaration in case block  no-case-declarations

/Users/catrielmuller/Dev/Kilo-Org/kilocode/cli/src/constants/providers/__tests__/models.test.ts
  514:31  warning  Unexpected any. Specify a different type                                   @typescript-eslint/no-explicit-any
  621:44  warning  'modelId' is defined but never used. Allowed unused args must match /^_/u  @typescript-eslint/no-unused-vars
  638:44  warning  'modelId' is defined but never used. Allowed unused args must match /^_/u  @typescript-eslint/no-unused-vars
  657:44  warning  'modelId' is defined but never used. Allowed unused args must match /^_/u  @typescript-eslint/no-unused-vars

/Users/catrielmuller/Dev/Kilo-Org/kilocode/cli/src/constants/providers/models.ts
  435:60  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

/Users/catrielmuller/Dev/Kilo-Org/kilocode/cli/src/constants/providers/settings.ts
  529:33  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

/Users/catrielmuller/Dev/Kilo-Org/kilocode/cli/src/host/ExtensionHost.ts
   24:27   warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   25:24   warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   26:21   warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   27:40   warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   43:47   warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   43:69   warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   59:45   warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  168:33   warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  328:15   warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  331:15   warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  352:27   warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  357:29   warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  362:28   warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  367:29   warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  372:28   warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  389:18   warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  390:22   warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  409:42   warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  416:70   warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  416:102  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  446:9    warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  449:16   warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  450:20   warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  454:22   warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  458:21   warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  462:22   warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  466:21   warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  556:49   warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  889:52   warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

/Users/catrielmuller/Dev/Kilo-Org/kilocode/cli/src/host/VSCode.ts
    22:30  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
    30:31  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
    30:47  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   330:88  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   331:13  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   475:42  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   475:50  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   481:61  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   497:21  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   511:65  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   514:84  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   529:17  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   536:19  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   650:40  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   685:94  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   706:29  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   711:31  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   748:35  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   771:42  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   952:24  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   953:58  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   954:52  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   955:54  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   956:53  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   974:48  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   978:45  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   980:36  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   984:44  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   988:42  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   993:43  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  1006:44  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  1135:17  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  1139:5   warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  1148:66  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  1163:28  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  1164:33  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  1226:28  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  1244:39  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  1276:40  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  1279:35  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  1383:24  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  1436:29  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  1437:59  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  1476:43  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  1490:6   warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  1528:44  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  1533:26  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  1538:28  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  1544:18  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  1545:34  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  1547:13  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  1598:56  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  1598:72  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  1600:18  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  1601:16  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  1605:28  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  1607:21  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  1608:19  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  1611:47  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  1614:21  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  1615:19  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  1655:20  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  1656:18  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  1662:31  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  1669:51  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  1670:36  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  1674:48  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  1675:36  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  1679:52  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  1684:43  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  1688:42  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  1692:50  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  1696:51  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  1700:44  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  1704:24  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  1708:19  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  1723:29  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  1724:33  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  1731:42  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  1731:52  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  1733:55  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  1733:65  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  1742:56  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  1769:97  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  1785:32  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  1786:29  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  1802:54  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  1821:42  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  1853:9   warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  1947:46  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  1947:54  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  2039:92  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  2040:17  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  2096:18  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

/Users/catrielmuller/Dev/Kilo-Org/kilocode/cli/src/host/__tests__/ExtensionHost.telemetry.test.ts
   17:46  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   34:46  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   46:30  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   56:46  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  138:46  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  197:30  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  207:46  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

/Users/catrielmuller/Dev/Kilo-Org/kilocode/cli/src/host/__tests__/console-interception.test.ts
  51:21  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

/Users/catrielmuller/Dev/Kilo-Org/kilocode/cli/src/host/__tests__/error-isolation.test.ts
   31:46  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   39:46  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   47:46  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   57:42  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   65:42  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   96:42  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  116:42  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  118:37  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  134:42  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  136:37  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  151:42  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  153:23  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  172:42  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  189:37  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  199:37  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

/Users/catrielmuller/Dev/Kilo-Org/kilocode/cli/src/services/__tests__/ExtensionService.test.ts
   16:27  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   17:23  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   18:21  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  138:46  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  149:15  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  160:21  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

/Users/catrielmuller/Dev/Kilo-Org/kilocode/cli/src/services/__tests__/approvalDecision.test.ts
  67:66  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

/Users/catrielmuller/Dev/Kilo-Org/kilocode/cli/src/services/autocomplete.ts
  413:19  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  463:19  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  557:78  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  641:19  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

/Users/catrielmuller/Dev/Kilo-Org/kilocode/cli/src/services/extension.ts
  124:57  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  176:39  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  176:53  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  300:33  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  349:38  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  353:40  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  364:39  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

/Users/catrielmuller/Dev/Kilo-Org/kilocode/cli/src/services/logs.ts
   14:27  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   73:32  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   73:38  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   84:29  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   87:28  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   97:52  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   97:74  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  102:36  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  108:69  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  119:93  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  158:16  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  169:13  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  200:14  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  271:73  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  278:74  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  285:74  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  292:73  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

/Users/catrielmuller/Dev/Kilo-Org/kilocode/cli/src/services/telemetry/TelemetryClient.ts
   17:29  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  129:67  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  167:67  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  194:89  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  232:34  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

/Users/catrielmuller/Dev/Kilo-Org/kilocode/cli/src/services/telemetry/TelemetryService.ts
  266:69  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  359:97  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  478:89  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  543:37  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

/Users/catrielmuller/Dev/Kilo-Org/kilocode/cli/src/services/telemetry/__tests__/telemetry.test.ts
  187:25  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  332:24  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

/Users/catrielmuller/Dev/Kilo-Org/kilocode/cli/src/services/telemetry/identity.ts
  253:38  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

/Users/catrielmuller/Dev/Kilo-Org/kilocode/cli/src/state/atoms/__tests__/approval.test.ts
  6:10  warning  'atom' is defined but never used. Allowed unused vars must match /^_/u  @typescript-eslint/no-unused-vars

/Users/catrielmuller/Dev/Kilo-Org/kilocode/cli/src/state/atoms/__tests__/keyboard.test.ts
   13:44  warning  'historyIndexAtom' is defined but never used. Allowed unused vars must match /^_/u  @typescript-eslint/no-unused-vars
  268:70  warning  Unexpected any. Specify a different type                                            @typescript-eslint/no-explicit-any
  302:41  warning  Unexpected any. Specify a different type                                            @typescript-eslint/no-explicit-any
  652:23  warning  Unexpected any. Specify a different type                                            @typescript-eslint/no-explicit-any
  680:23  warning  Unexpected any. Specify a different type                                            @typescript-eslint/no-explicit-any

/Users/catrielmuller/Dev/Kilo-Org/kilocode/cli/src/state/atoms/actions.ts
  186:87  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

/Users/catrielmuller/Dev/Kilo-Org/kilocode/cli/src/state/atoms/approval.ts
  365:51  warning  'set' is defined but never used. Allowed unused args must match /^_/u  @typescript-eslint/no-unused-vars
  376:50  warning  'set' is defined but never used. Allowed unused args must match /^_/u  @typescript-eslint/no-unused-vars
  387:59  warning  'set' is defined but never used. Allowed unused args must match /^_/u  @typescript-eslint/no-unused-vars

/Users/catrielmuller/Dev/Kilo-Org/kilocode/cli/src/state/atoms/config.ts
  443:96  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  451:45  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

/Users/catrielmuller/Dev/Kilo-Org/kilocode/cli/src/state/atoms/effects.ts
  36:80  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  46:37  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

/Users/catrielmuller/Dev/Kilo-Org/kilocode/cli/src/state/atoms/extension.ts
  68:37  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

/Users/catrielmuller/Dev/Kilo-Org/kilocode/cli/src/state/atoms/history.ts
  119:55  warning  'set' is defined but never used. Allowed unused args must match /^_/u  @typescript-eslint/no-unused-vars

/Users/catrielmuller/Dev/Kilo-Org/kilocode/cli/src/state/atoms/keyboard.ts
  328:34  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  328:44  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  376:34  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  376:44  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  434:38  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  434:48  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  487:33  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  487:43  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  520:35  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  520:45  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  640:35  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  640:45  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

/Users/catrielmuller/Dev/Kilo-Org/kilocode/cli/src/state/atoms/ui.ts
  434:53  warning  'get' is defined but never used. Allowed unused args must match /^_/u  @typescript-eslint/no-unused-vars
  434:58  warning  'set' is defined but never used. Allowed unused args must match /^_/u  @typescript-eslint/no-unused-vars

/Users/catrielmuller/Dev/Kilo-Org/kilocode/cli/src/state/hooks/__tests__/useTerminal.test.ts
  35:79  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  42:89  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

/Users/catrielmuller/Dev/Kilo-Org/kilocode/cli/src/state/hooks/useCommandContext.ts
   30:26  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   87:59  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   92:34  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  138:57  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

/Users/catrielmuller/Dev/Kilo-Org/kilocode/cli/src/state/hooks/useModelSelection.ts
   40:37  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  130:50  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

/Users/catrielmuller/Dev/Kilo-Org/kilocode/cli/src/state/hooks/useWebviewMessage.ts
   90:33  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  203:18  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

/Users/catrielmuller/Dev/Kilo-Org/kilocode/cli/src/types/messages.ts
   14:10  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   16:17  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   17:26  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   18:17  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   28:21  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   30:26  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   36:17  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   49:15  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   50:13  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  324:17  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  381:15  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  390:17  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

/Users/catrielmuller/Dev/Kilo-Org/kilocode/cli/src/ui/components/StatusBar.tsx
  44:9  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

/Users/catrielmuller/Dev/Kilo-Org/kilocode/cli/src/ui/components/__tests__/StatusBar.test.tsx
   28:53  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  119:53  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  139:53  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  153:53  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  190:53  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  211:26  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  236:54  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

/Users/catrielmuller/Dev/Kilo-Org/kilocode/cli/src/ui/messages/extension/__tests__/ExtensionMessageRow.test.tsx
  112:28  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  205:28  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  221:24  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

/Users/catrielmuller/Dev/Kilo-Org/kilocode/cli/src/ui/messages/extension/tools/ToolEditedExistingFileMessage.tsx
  31:44  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

/Users/catrielmuller/Dev/Kilo-Org/kilocode/cli/src/ui/messages/extension/types.ts
  29:21  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  41:20  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  62:13  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

/Users/catrielmuller/Dev/Kilo-Org/kilocode/cli/src/ui/messages/extension/utils.ts
  8:38  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

/Users/catrielmuller/Dev/Kilo-Org/kilocode/cli/src/ui/messages/utils/messageCompletion.ts
  123:75  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

/Users/catrielmuller/Dev/Kilo-Org/kilocode/cli/src/ui/providers/KeyboardProvider.tsx
  163:44  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

/Users/catrielmuller/Dev/Kilo-Org/kilocode/cli/src/ui/utils/keyParsing.ts
  326:39  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

/Users/catrielmuller/Dev/Kilo-Org/kilocode/cli/src/ui/utils/terminalCapabilities.ts
  12:7  warning  'kittyEnabled' is assigned a value but never used. Allowed unused vars must match /^_/u  @typescript-eslint/no-unused-vars

/Users/catrielmuller/Dev/Kilo-Org/kilocode/cli/src/utils/__tests__/git.test.ts
   31:52  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   47:52  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   65:52  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
   79:52  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  100:52  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  111:52  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  121:52  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  143:52  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  156:52  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  169:52  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  182:52  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  192:52  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  271:52  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  282:52  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  293:52  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  303:52  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

/Users/catrielmuller/Dev/Kilo-Org/kilocode/cli/src/utils/__tests__/providers.test.ts
  101:51  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

/Users/catrielmuller/Dev/Kilo-Org/kilocode/cli/src/utils/context.ts
  44:9   warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  95:40  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

/Users/catrielmuller/Dev/Kilo-Org/kilocode/cli/src/utils/providers.ts
  14:35  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

✖ 345 problems (0 errors, 345 warnings)
```

### PR DESCRIPTION
**Pull request by catrielmuller**
## Context

Resolve: #3493 

## Screenshots

image
image

## How to Test

- pnpm run lint
- pnpm run check-types
- pnpm run test

### CODE REVIEW

File: cli/src/config/types.ts [hunk 1]
```diff
@@ -110,7 +110,7 @@ export interface ProviderConfig {
 	id: string
 	provider: ProviderName
 	// Provider-specific fields
-	[key: string]: any
+	[key: string]: unknown
```
Comment (iscekic) [inline cli/src/config/types.ts]: I wonder if it's too much work, but we could make a zod schema which is a union of each specific provider and then use that as the type here, as well as reuse the schema for validation.

File: cli/src/constants/providers/__tests__/models.test.ts [hunk 2]
```diff
@@ -511,7 +511,7 @@ describe("Static Provider Models", () => {
 		})
 
 		it("should handle null price", () => {
```
Comment (iscekic) [inline cli/src/constants/providers/__tests__/models.test.ts:512]: I'd argue it shouldn't, if the type it accepts is number the compiler should complain when there's a type mismatch

File: cli/src/commands/profile.ts [hunk 3]
```diff
@@ -44,6 +44,16 @@ async function showProfile(context: any): Promise<void> {
...
+	if (!profileData) {
+		addMessage({
+			id: Date.now().toString(),
+			type: "error",
+			content: "No profile data available",
+			ts: Date.now(),
+		})
+		return
+	}
+
```
Comment (RSO) [inline cli/src/commands/profile.ts:56]: This feels new?

File: cli/src/commands/teams.ts [hunk 4]
```diff
@@ -81,8 +81,12 @@ async function listTeams(context: any): Promise<void> {
 		const isCurrent = org.id === currentOrgId
 		content += `${isCurrent ? "→ " : "  "}${normalizeTeamName(org.name)}${isCurrent ? " (current)" : ""}\n`
 	}
-	content += `\nUse \`/teams select ${normalizeTeamName(organizations[0].name)}\` select the ${organizations[0].name} profile\n`
+	// kilocode_change start
```
Comment (RSO) [inline cli/src/commands/teams.ts]: This is the `cli` directory so I don't think we need it?

File: cli/src/commands/teams.ts [hunk 5]
```diff
@@ -81,8 +81,12 @@ async function listTeams(context: any): Promise<void> {
...
+	if (organizations.length > 0) {
+		content += `\nUse \`/teams select ${normalizeTeamName(organizations[0]!.name)}\` to select a team profile\n`
+	}
 	content += `Use \`/teams select personal\` to switch to personal account\n`
+	// kilocode_change end
```
Comment (RSO) [inline cli/src/commands/teams.ts]: Same

File: cli/src/config/mapper.ts [hunk 6]
```diff
@@ -61,35 +62,35 @@ function mapProviderToApiConfig(provider: ProviderConfig): ProviderSettings {
...
+			return (provider.requestyModelId as string | undefined) || ""
 		case "vercel-ai-gateway":
-			return provider.vercelAiGatewayModelId || ""
+			return (provider.vercelAiGatewayModelId as string | undefined) || ""
 		case "io-intelligence":
-			return provider.ioIntelligenceModelId || ""
+			return (provider.ioIntelligenceModelId as string | undefined) || ""
 		default:
-			return provider.apiModelId || provider.modelId || ""
+			return (provider.apiModelId as string | undefined) || (provider.modelId as string | undefined) || ""
```
Comment (RSO) [inline cli/src/config/mapper.ts]: This one I don't get 🤔 maybe it's cleaner to just cast the whole method to a string return value?

File: cli/src/config/types.ts (hunk 1 above)
Comment (RSO) [reply cli/src/config/types.ts]: Yeah that definitely sounds like something we want at some point

File: cli/src/host/__tests__/console-interception.test.ts [hunk 7]
```diff
@@ -48,7 +48,7 @@ describe("ExtensionHost Console Interception", () => {
 
 	it("should clean up global __interceptedConsole on deactivation", async () => {
 		// Verify that the global console interception is cleaned up
-		expect((global as any).__interceptedConsole).toBeUndefined()
+		expect((global as unknown as { __interceptedConsole?: unknown }).__interceptedConsole).toBeUndefined()
```
Comment (RSO) [inline cli/src/host/__tests__/console-interception.test.ts]: Isn't there another way to write this? Something like `"__interceptedConsole" in global` or something like that? 🤔

File: cli/src/state/atoms/actions.ts [hunk 8]
```diff
@@ -278,7 +291,8 @@ export const sendPrimaryButtonClickAtom = atom(null, async (get, set) => {
  */
 export const sendSecondaryButtonClickAtom = atom(null, async (get, set) => {
 	const message: WebviewMessage = {
-		type: "secondaryButtonClick",
+		type: "askResponse",
+		askResponse: "noButtonClicked",
```
Comment (RSO) [inline cli/src/state/atoms/actions.ts:295]: These seem surprising/scary to me, as they definitely change the structure of the message. Also we change the secondaryButton to noButton?

File: cli/src/state/hooks/useCommandInput.ts [hunk 9]
```diff
@@ -266,6 +267,7 @@ export function useCommandInput(): UseCommandInputReturn {
 		} else if (state.type === "argument") {
 			// Create command context for argument providers
 			const commandContext = {
+				config,
```
Comment (RSO) [inline cli/src/state/hooks/useCommandInput.ts:271]: This feels new?

File: cli/src/state/hooks/useCommandInput.ts [hunk 10]
```diff
@@ -304,6 +306,7 @@ export function useCommandInput(): UseCommandInputReturn {
 		setFileMentionSuggestionsAction,
 		setFileMentionContextAction,
 		clearFileMentionAction,
+		config,
```
Comment (RSO) [inline cli/src/state/hooks/useCommandInput.ts:311]: This feels new as well

File: cli/src/utils/notifications.ts [hunk 11]
```diff
@@ -28,12 +28,12 @@ export async function fetchKilocodeNotifications({
...
 	}
 
-	if (!kilocodeToken) {
+	if (!kilocodeToken || typeof kilocodeToken !== "string") {
 		logs.debug("No kilocode token found, skipping notification fetch", "fetchKilocodeNotifications")
 		return []
 	}
 
-	const url = getKiloUrlFromToken("https://api.kilocode.ai/api/users/notifications", kilocodeToken)
+	const url = getKiloUrlFromToken("https://api.kilocode.ai/api/users/notifications", kilocodeToken as string)
```
Comment (RSO) [inline cli/src/utils/notifications.ts]: I don't think this `as string` is needed? The `typeof` above should cover this, right?

File: src/core/prompts/sections/custom-instructions.ts [hunk 12]
```diff
@@ -273,7 +273,9 @@ async function loadAgentRulesFile(cwd: string): Promise<string> {
 					await resolveSymLink(agentPath, fileInfo, 0)
 
 					// Extract the resolved path from fileInfo
-					if (fileInfo.length > 0) {
+					// kilocode_change start - add null check for fileInfo[0]
+					if (fileInfo.length > 0 && fileInfo[0]) {
+						// kilocode_change end
```
Comment (RSO) [inline src/core/prompts/sections/custom-instructions.ts:278]: Do we really need changes outside of the CLI folder?

**Review by RSO — APPROVED** [review]
Added some comments about changes that seem sus, but other than that I like seeing all the `any`s get replaced with actual types 😍

File: cli/src/commands/profile.ts (hunk 3 above)
Comment (catrielmuller) [reply cli/src/commands/profile.ts:56]: Yes, because the profileData can be null, it's a safe check

File: cli/src/commands/teams.ts (hunk 4 above)
Comment (catrielmuller) [reply cli/src/commands/teams.ts]: Removed

File: cli/src/commands/teams.ts (hunk 5 above)
Comment (catrielmuller) [reply cli/src/commands/teams.ts]: Removed

File: cli/src/config/types.ts (hunk 1 above)
Comment (catrielmuller) [reply cli/src/config/types.ts]: Added definitions to each providers

File: cli/src/config/mapper.ts (hunk 6 above)
Comment (catrielmuller) [reply cli/src/config/mapper.ts]: Added type definitions

File: src/core/prompts/sections/custom-instructions.ts (hunk 12 above)
Comment (catrielmuller) [reply src/core/prompts/sections/custom-instructions.ts:278]: This change it's inside of the extension folder -> `src/core/prompts/sections/custom-instructions.ts`

File: cli/src/state/hooks/useCommandInput.ts (hunk 10 above)
Comment (catrielmuller) [reply cli/src/state/hooks/useCommandInput.ts:311]: This was added on the theme PR

File: cli/src/state/atoms/actions.ts (hunk 8 above)
Comment (catrielmuller) [reply cli/src/state/atoms/actions.ts:295]: This was changed in base of the type definitions that come from the extension.

File: cli/src/utils/notifications.ts (hunk 11 above)
Comment (catrielmuller) [reply cli/src/utils/notifications.ts]: Removed now that we have proper types on the providersCOnfig

File: cli/src/host/__tests__/console-interception.test.ts (hunk 7 above)
Comment (catrielmuller) [reply cli/src/host/__tests__/console-interception.test.ts]: Fixed.

File: cli/src/state/hooks/useCommandInput.ts (hunk 9 above)
Comment (catrielmuller) [reply cli/src/state/hooks/useCommandInput.ts:271]: was introduced by the Theme PR
