### PR TITLE
Morph FastApply updates

### LINKED ISSUE #1848: Failed to edit file
### Description

I am facing edit failed related issue a lot. Edit failed, failed to apply_diff,
Kilo Code tried to use edit_file without value for required parameter 'code_edit'. Retrying...

Image

### LINKED ISSUE #2006: Morph FastApply Bug: Not configured properly and can't add API key
### Description

Trying the experimental fast apply by morphllm. Everytime i paste my api key, it gets cleared immediately so I can't even use the feature. Even if that api key is optional, the model can't use it. 

Image

### LINKED ISSUE #2034: Gemini 2.5 Flash always fails to edit file
### Description

I have a custom mode for documentation editing and I use Gemini CLI as provider with model Gemini 2.5 Flash Reasoning. This model always fails to edit file. Gemini 2.5 Pro with Gemini CLI on the other hand has no issues editing files.  Please see below errors. 

```
Error
Kilo Code tried to use edit_file without value for required parameter 'code_edit'. Retrying...


Kilo Code is having trouble...
This may indicate a failure in the model's thought process or inability to use a tool properly, which can be mitigated with some user guidance (e.g. "Try breaking down the task into smaller steps").
```

Image
Image

### PR DESCRIPTION
**Pull request by chrarnoldus**
Fixes: https://github.com/Kilo-Org/kilocode/issues/2034
Fixes: https://github.com/Kilo-Org/kilocode/issues/2006
Fixes: https://github.com/Kilo-Org/kilocode/issues/1848

### CODE REVIEW

**Comment by bhaktatejas922** [comment]
looks good to me!

File: src/core/config/ProviderSettingsManager.ts [hunk 1]
```diff
@@ -157,6 +160,14 @@ export class ProviderSettingsManager {
 					isDirty = true
 				}
 
+				// kilocode_change start
+				if (!providerProfiles.migrations.morphApiKeyMigrated) {
+					const result = await migrateMorphApiKey(this.context, providerProfiles)
+					providerProfiles.migrations.morphApiKeyMigrated = true
+					isDirty ||= result
```
Comment (hassoncs) [inline src/core/config/ProviderSettingsManager.ts:167]: oh cool, I didn't realize our repo had support for `||=` 👏

File: src/shared/getApiMetrics.ts [hunk 2]
```diff
@@ -63,6 +68,21 @@ export function getApiMetrics(messages: ClineMessage[]) {
...
+				const fastApplyResult = safeJsonParse<ClineSayTool>(message.text)?.fastApplyResult
+				if (fastApplyResult?.tokensIn) {
+					result.totalTokensIn += fastApplyResult.tokensIn
+				}
+				if (fastApplyResult?.tokensOut) {
+					result.totalTokensIn += fastApplyResult.tokensOut
+				}
+				if (fastApplyResult?.cost) {
+					result.totalTokensIn += fastApplyResult.cost
+				}
```
Comment (hassoncs) [inline src/shared/getApiMetrics.ts]: Should these be `totalTokensIn/totalTokensOut/totalCost`?
```suggestion
				result.totalTokensIn += fastApplyResult?.tokensIn ?? 0
				result.totalTokensOut += fastApplyResult.tokensOut ?? 0
				result.totalCost += fastApplyResult.cost ?? 0
```

**Review by hassoncs — DISMISSED** [review]
Looks good! Just one comment that might require a change `totalTokensIn/totalTokensOut/totalCost`

File: src/shared/getApiMetrics.ts (hunk 2 above)
Comment (chrarnoldus) [reply src/shared/getApiMetrics.ts]: yes

File: src/core/config/ProviderSettingsManager.ts (hunk 1 above)
Comment (chrarnoldus) [reply src/core/config/ProviderSettingsManager.ts:167]: any reason why it might not have it?

Comment (hassoncs) [reply src/core/config/ProviderSettingsManager.ts:167]: the tsconfig / linting just needs to be setup for it. Nothing crazy

**Review by hassoncs — APPROVED** [review]
Nice!
