### PR TITLE
Include tool calls and results in the API conversation history

### LINKED ISSUE #3237: Native (json) tools calls missing the assistant message between tool calls
### Plugin Type

VSCode Extension

### App Version

Version: 4.109.2 (d6adecad)

### Description

This issue happens when the model using json tool calls with no user interaction, with xlm tools there is no issue

Image

### Reproduction steps

1. create any prompt with json tool calls

### Provider

Kilo Code

### Model

Kimi k2-0905 Moonshot ai provider

### System Information

_No response_

### PR DESCRIPTION
**Pull request by chrarnoldus**
should fix https://github.com/Kilo-Org/kilocode/issues/3237 and seems to make models less confused about what happened

### CODE REVIEW

File: src/core/task/Task.ts [hunk 1]
```diff
@@ -2423,10 +2427,19 @@ export class Task extends EventEmitter<TaskEvents> implements TaskLike {
...
+					}
+					for (const toolUse of assistantToolUses) {
+						assistantMessageContent.push(toolUse)
+					}
 					await this.addToApiConversationHistory({
 						role: "assistant",
-						content: [{ type: "text", text: assistantMessage }],
+						content: assistantMessageContent,
 					})
+					// kilocode_change start
```
Comment (chrarnoldus) [inline src/core/task/Task.ts]:
```suggestion
					// kilocode_change end
```

File: src/core/assistant-message/kilocode/native-tool-call.ts [hunk 2]
```diff
@@ -57,3 +57,24 @@ export function parseDoubleEncodedParams(obj: any): any {
 	// Primitive types (number, boolean, etc.) return as-is
 	return obj
 }
+
+const knownWrapperPropertyNames = [
+	"arguments", // seen with qwen3-coder
+	"result", // seen with gemini-2.5-flash, haiku-4.5, sonnet-4.5
+]
+
+export function removeWrapperObject(toolName: string, parsedArgs: Record<string, unknown>, nestingLevel: number) {
```
Comment (chrarnoldus) [inline src/core/assistant-message/kilocode/native-tool-call.ts]: I noticed that the actual arguments are often wrapped in objects with a single property, sometimes multiple levels deep.

There are probably less hacky ways to do this, I was thinking of defining the parameters as zod4 schemas so we can look for an object that matches the schema.

**Comment by chrarnoldus** [comment]
@mcowger fyi

**Review by hassoncs — APPROVED** [review]
looks good to me! I tested it out for a while and haiku 4.5 is working pretty well!

File: src/core/task/Task.ts [hunk 3]
```diff
@@ -2423,10 +2427,19 @@ export class Task extends EventEmitter<TaskEvents> implements TaskLike {
...
 					}
 
+					// kilocode_change start: also add tool calls to history
+					const assistantMessageContent = new Array<Anthropic.Messages.ContentBlockParam>()
+					if (assistantMessage) {
+						assistantMessageContent.push({ type: "text", text: assistantMessage })
+					}
+					for (const toolUse of assistantToolUses) {
+						assistantMessageContent.push(toolUse)
+					}
```
Comment (chrarnoldus) [inline src/core/task/Task.ts]:
```suggestion
					assistantMessageContent.push(...assistantToolUses)
```

**Comment by chrarnoldus** [comment]
> looks good to me! I tested it out for a while and haiku 4.5 is working pretty well!

did you get any read_file errors?

**Comment by hassoncs** [comment]
I didn't get any errors! I'll keep pushing it around for a bit
