### PR TITLE
various autocomplete fixes

### LINKED ISSUE #3423: Disabling Autocomplete does not work (Consumes tokens)
### Plugin Type

VSCode Extension

### App Version

v4.113.1

### Description

Even though the Autocomplete feature is disabled, it still activates when opening a file. This unexpected behavior triggers token usage, resulting in unnecessary costs.

Image

Image

### Reproduction steps

1. Disable the Autocomplete feature in the extension settings.
2. Open any file in the editor.
3. Observe that the gutter animation appears, indicating Autocomplete activity.
4. Check the Kilo Code panel — it shows token usage, confirming that Autocomplete is still running

### Provider

Kilo Code

### Model

mistralai/codestral-2508

### System Information

OS: Ubuntu 24.04
Editor: Windsurf

### PR DESCRIPTION
**Pull request by markijbema**
which hopefully fixes people not being able to disable autocomplete. As I am not able to reproduce the bug I'm going for defense in depth here and try to make every part which is suspicious better

Attempt to fix https://github.com/Kilo-Org/kilocode/issues/3423

### CODE REVIEW

File: src/services/ghost/GhostServiceManager.ts [hunk 1]
```diff
@@ -26,7 +26,6 @@ export class GhostServiceManager {
 	private ghostContext: GhostContext
 	private cursorAnimation: GhostGutterAnimation
 
-	private enabled: boolean = true
```
Comment (markijbema) [inline src/services/ghost/GhostServiceManager.ts:29]: this is probably a remnant from the old feature toggle for inline assist. It is always true, so it confused me for a bit

File: src/services/autocomplete/AutocompleteProvider.ts [hunk 2]
```diff
@@ -71,7 +71,7 @@ export class AutocompleteProvider {
 			provider: this.getCurrentProviderName(),
 			model: this.getCurrentModelName(),
 		}
-		await ContextProxy.instance?.setValues?.({ ghostServiceSettings: settingsWithModelInfo })
```
Comment (markijbema) [inline src/services/autocomplete/AutocompleteProvider.ts:74]: this could never be null, changed code so it's clear this isnt a noop

File: src/services/ghost/GhostServiceManager.ts [hunk 3]
```diff
@@ -60,6 +59,7 @@ export class GhostServiceManager {
 			this.updateCostTracking.bind(this),
 			this.ghostContext,
 			this.cursorAnimation,
+			() => this.settings,
```
Comment (markijbema) [inline src/services/ghost/GhostServiceManager.ts:62]: avoid at least one sync by letting the inline ghost completions request latest version

File: src/services/ghost/GhostServiceManager.ts [hunk 4]
```diff
@@ -121,22 +121,21 @@ export class GhostServiceManager {
...
+		const shouldBeRegistered = this.settings?.enableAutoTrigger ?? false
+
+		if (shouldBeRegistered && !this.inlineCompletionProviderDisposable) {
+			// Register the provider
 			this.inlineCompletionProviderDisposable = vscode.languages.registerInlineCompletionItemProvider(
 				"*",
 				this.inlineCompletionProvider,
 			)
 			this.context.subscriptions.push(this.inlineCompletionProviderDisposable)
+		} else if (!shouldBeRegistered && this.inlineCompletionProviderDisposable) {
```
Comment (markijbema) [inline src/services/ghost/GhostServiceManager.ts:134]: disable ghost completion if setting is off

File: src/services/ghost/GhostServiceManager.ts [hunk 5]
```diff
@@ -284,8 +277,41 @@ export class GhostServiceManager {
 			await this.load()
 		}
 
-		// Trigger the inline completion provider
-		await vscode.commands.executeCommand("editor.action.inlineSuggest.trigger")
```
Comment (markijbema) [inline src/services/ghost/GhostServiceManager.ts:288]: moved the code here and changed functionality a bit (tbh i think we should remove this functionality, it is just autocomplete without the auto) so that we don't rely on the inline completion provider being registered

File: src/services/ghost/classic-auto-complete/GhostInlineCompletionProvider.ts [hunk 6]
```diff
@@ -232,7 +230,23 @@ export class GhostInlineCompletionProvider implements vscode.InlineCompletionIte
...
+		const isAutoTriggerEnabled = settings?.enableAutoTrigger ?? false
+
+		if (!isAutoTriggerEnabled) {
+			return []
+		}
+
+		return this.provideInlineCompletionItems_Internal(document, position, _context, _token)
+	}
+
+	public async provideInlineCompletionItems_Internal(
```
Comment (markijbema) [inline src/services/ghost/classic-auto-complete/GhostInlineCompletionProvider.ts:246]: extracted function for cmd-l, so we can be stricter with disabling provideInlineCompletions

File: src/services/ghost/classic-auto-complete/GhostInlineCompletionProvider.ts [hunk 7]
```diff
@@ -232,7 +230,23 @@ export class GhostInlineCompletionProvider implements vscode.InlineCompletionIte
 	public async provideInlineCompletionItems(
 		document: vscode.TextDocument,
 		position: vscode.Position,
-		context: vscode.InlineCompletionContext,
+		_context: vscode.InlineCompletionContext,
+		_token: vscode.CancellationToken,
+	): Promise<vscode.InlineCompletionItem[] | vscode.InlineCompletionList> {
+		const settings = this.getSettings()
+		const isAutoTriggerEnabled = settings?.enableAutoTrigger ?? false
```
Comment (markijbema) [inline src/services/ghost/classic-auto-complete/GhostInlineCompletionProvider.ts:237]: only check settings, no way around it now

File: webview-ui/src/components/kilocode/settings/GhostServiceSettings.tsx [hunk 8]
```diff
@@ -1,25 +1,27 @@
...
 import { Trans } from "react-i18next"
 import { Bot, Zap } from "lucide-react"
 import { cn } from "@/lib/utils"
 import { SectionHeader } from "../../settings/SectionHeader"
 import { Section } from "../../settings/Section"
 import { GhostServiceSettings } from "@roo-code/types"
-import { SetCachedStateField } from "../../settings/types"
 import { vscode } from "@/utils/vscode"
-import { ControlledCheckbox } from "../common/ControlledCheckbox"
+import { VSCodeCheckbox } from "@vscode/webview-ui-toolkit/react"
```
Comment (markijbema) [inline webview-ui/src/components/kilocode/settings/GhostServiceSettings.tsx:11]: Because I cannot reproduce the problem I don't know what the problem is. Most of the fixes are assuming the internal state of autocomplete is disabled, and that that isnt respected by the code. Another explanation could be that the autocomplete is actually enabled, and that this is shown incorrectly in the settings.

Since the two hard things in CS are naming, caching and off by one errors I removed the caching here

File: .changeset/every-brooms-play.md [hunk 9]
```diff
@@ -0,0 +1,5 @@
+---
+"kilo-code": patch
+---
+
+Minor improvements to autocomplete internal state handling
```
Comment (markijbema) [inline .changeset/every-brooms-play.md:5]: in a sense this is the major releasenote, but since i cannot reproduce i cannot be sure we fix anything (but wanted to have a releasenote for traceability)

File: .changeset/warm-berries-search.md [hunk 10]
```diff
@@ -0,0 +1,5 @@
+---
+"kilo-code": minor
+---
+
+Cmd-L now directly inserts instead of showing as ghost text
```
Comment (markijbema) [inline .changeset/warm-berries-search.md:5]: added this since it is a functional change.

File: src/services/ghost/GhostServiceManager.ts [hunk 11]
```diff
@@ -284,8 +277,41 @@ export class GhostServiceManager {
...
+		// Call the inline completion provider directly with manual trigger context
+		const position = editor.selection.active
+		const context: vscode.InlineCompletionContext = {
+			triggerKind: vscode.InlineCompletionTriggerKind.Invoke,
+			selectedCompletionInfo: undefined,
+		}
+		const tokenSource = new vscode.CancellationTokenSource()
+
+		try {
+			const completions = await this.inlineCompletionProvider.provideInlineCompletionItems_Internal(
```
[the remark this answers is not in the document]
Comment (markijbema) [reply src/services/ghost/GhostServiceManager.ts:289]: That is intentional, kilocode change doesnt apply for everything in ghost

**Review by chrarnoldus — APPROVED** [review]
