### PR TITLE
Fix allowed commands import/export 

### LINKED ISSUE #784: "Allowed Auto-Execute Commands" Are Not Included in Settings Export/Import
### Description

I've observed that the "Allowed Auto-Execute Commands" list is not being carried over when using the export/import settings functionality. This makes it difficult to replicate a trusted Kilo setup on a new instance without manually re-entering each command.

**Steps to Reproduce:**

1.  Add custom commands to the "Allowed Auto-Execute Commands" list in Klio settings.
2.  Export the configuration.
3.  On a fresh installation of Kilo, import the previously exported configuration file.

**Expected Behavior:**

I expect all settings, including the "Allowed Auto-Execute Commands" list, to be successfully imported, fully restoring my previous configuration.

**Actual Behavior:**

While most settings (like profiles, auto-approve actions, etc.) are imported correctly, the "Allowed Auto-Execute Commands" list is empty after the import.

**Environment:**

* Kilo Version: 4.38.1 (6eee34ca)

### PR DESCRIPTION
**Pull request by catrielmuller**
## Context

- Resolve [#784](https://github.com/Kilo-Org/kilocode/issues/784)

## Implementation

- Updated the webview handler to use a nullish coalescing operator when updating allowed commands.
- Combined allowed commands from global state and workspace configuration in ClineProvider to remove duplicates.

## How to Test

- Setup a set of commands
- Save the config
- Export the Kilo config on About Kilo settings section
- Remove all the commands
- Import the exported config

### CODE REVIEW

File: src/core/webview/ClineProvider.ts [hunk 1]
```diff
@@ -1371,7 +1372,11 @@ export class ClineProvider extends EventEmitter<ClineProviderEvents> implements
 		} = await this.getState()
 
 		const machineId = vscode.env.machineId
-		const allowedCommands = vscode.workspace.getConfiguration(Package.name).get<string[]>("allowedCommands") || []
+		const allowedCommandsState = allowedCommands || []
+		const allowedCommandsWorkspace =
+			vscode.workspace.getConfiguration(Package.name).get<string[]>("allowedCommands") || []
+		const allowedCommandsCombined = [...new Set([...allowedCommandsState, ...allowedCommandsWorkspace])]
```
Comment (hassoncs) [inline src/core/webview/ClineProvider.ts:1427]: Since this is shared with Roo, maybe wrap this in `//kilocode_change start/end` comment? But it looks like it might be a bug in Roo too, so maybe we could open this PR against them instead?

**Comment by chrarnoldus** [comment]
Approved if you add the `//kilocode_change` markers.

Looks like a candidate for upstreaming indeed.

**Comment by kevinvandijk** [comment]
Don't forget to add a changeset so it will show up in the changelog!

File: src/core/webview/ClineProvider.ts (hunk 1 above)
Comment (catrielmuller) [reply src/core/webview/ClineProvider.ts:1427]: > Since this is shared with Roo, maybe wrap this in `//kilocode_change start/end` comment? But it looks like it might be a bug in Roo too, so maybe we could open this PR against them instead?

Added `//kilocode_change` comments

**Comment by catrielmuller** [comment]
@chrarnoldus @kevinvandijk Added the changeset and the change markers

**Review by chrarnoldus — APPROVED** [review]
