### PR TITLE
fix(virtual-quota): display active model in UI for the frontend

### LINKED ISSUE #1903: Virtual provider not using chosen profiles
### Description

Which app version are you using (e.g. v3.3.1)? 
Kilo Code 4.79.2
VS Code 1.103.0

Which API Provider are you using (e.g. Kilo, OpenRouter, Anthropic)? Which Model are you using (e.g. Claude 3.7 Sonnet)? 
Profile 1: Gemini (Gemini 2.5 Pro)
Profile 2: Gemini (Gemini 2.5 Flash)
Profile 3: Kilo Code (Gemini 2.5 Flash)

Steps to reproduce? 
Using https://x.com/Kilo_Code/status/1954892714262065199 as my guide, I created 3 profiles with the above providers and models. I then created a profile with "Virtual Quota Fallback" as the profile and set the usage limits. When I went to send a prompt, I selected "Virtual Provider 1" and noticed that the model shown was "Claude Sonnet 4 20250514" which I have never used. I tried to send a prompt but it never did anything.

I have done something wrong in the setup or is this a bug?

Screenshots?

Image
Image
Image
Image
Image

### LINKED ISSUE #1981: Wrong token limit in task with Virtual Quota Fallback provider
### Description

I have Virtual Quota Fallback provider that uses Gemini models. 
The task reports 200K tokens when they should be 1M.

Image

### PR DESCRIPTION
**Pull request by ivanarifin**
## Context

Help user to know the active model while using the virtual quota fallback with correct model name and correct context window

## Implementation

When the backend switches the model, it now sends out a "model has changed" signal by emitting event.
The main application logic catches this signal and immediately tells the user interface to refresh itself.
The user interface then updates the display to show the name of the new, currently active model.
This will also keep the backend and the frontend active model in sync

## Screenshots

Screenshot 2025-10-10 at 12 40 08

## How to Test

Use virtual quota fallback as a provider

## Get in Touch

ivanarifin

### CODE REVIEW

**Comment by ivanarifin** [comment]
Hey matt @mcowger, would you mind testing this PR? tagging you here because you are the creator of the feature

**Comment by mcowger** [comment]
Will give it a shot tomorrow.  Thanks for the ping.

**Review by mcowger — COMMENTED** [review]
I took a try with this.   It does appear to switch the displayed information for the active model in the task timeline view, but only for the *first* change.   

E.g., If I configured:

1. qwen3-coder-plus (128kl)
2. gemini-2.5-flash (1M)
3. gpt-5-codex (400k)
5. qwen3-coder (262K)

The context timeline at the top shfts from 128K to 1M as expected on the first transition.   However, subsequent transitions occur (in that the request is sent to the correct profile), but the state of the context tracker doesn't change and remains at 1M context.

**Comment by ivanarifin** [comment]
> I took a try with this. It does appear to switch the displayed information for the active model in the task timeline view, but only for the _first_ change.
> 
> E.g., If I configured:
> 
>     1. qwen3-coder-plus (128kl)
> 
>     2. gemini-2.5-flash (1M)
> 
>     3. gpt-5-codex (400k)
> 
>     4. qwen3-coder (262K)
> 
> 
> The context timeline at the top shfts from 128K to 1M as expected on the first transition. However, subsequent transitions occur (in that the request is sent to the correct profile), but the state of the context tracker doesn't change and remains at 1M context.

@mcowger 
I can't seem to reproduce your issue
Here is my testing with 4 profiles and all RPM set to 1


https://github.com/user-attachments/assets/4a0b3e49-a028-47db-8ff9-1cef413c3edc

**Comment by mcowger** [comment]
Very strange.  

I'll give it another try tonight and see if I can grab some logs.

**Comment by mcowger** [comment]
I was wrong - I think I may have been testing in the wrong window.

Confirmed both the context window tracker, as well as the quick picker by the chat window change as expected.  This also appears to fix the context condensing bug.

Well done!

The only thing I think you need here is the `//kilocode_change` tags.

@chrarnoldus this works well for me!

**Comment by ivanarifin** [comment]
well I was actually working on the context condensing bug at first, then I thought, why not also fix the UI

**Comment by ivanarifin** [comment]
@chrarnoldus any chance this will be merged?

File: src/api/providers/virtual-quota-fallback.ts [hunk 1]
```diff
@@ -2,6 +2,7 @@
 import { Anthropic } from "@anthropic-ai/sdk"
 import { z } from "zod"
 import * as vscode from "vscode"
+import EventEmitter from "events" //kilocode_change
```
Comment (chrarnoldus) [inline src/api/providers/virtual-quota-fallback.ts]:
```suggestion
import EventEmitter from "events"
```

this file already has a kilocode_change marker at the top

File: src/core/task/Task.ts [hunk 2]
```diff
@@ -366,6 +368,12 @@ export class Task extends EventEmitter<TaskEvents> implements TaskLike {
 
 		this.apiConfiguration = apiConfiguration
 		this.api = buildApiHandler(apiConfiguration)
+		//kilocode_change: Listen for model changes in virtual quota fallback
+		if (this.api instanceof VirtualQuotaFallbackHandler) {
```
Comment (chrarnoldus) [inline src/core/task/Task.ts:378]: There are other places where `Task.api` is assigned (in `ClineProvider`), do we need this logic there as well?

Comment (ivanarifin) [reply src/core/task/Task.ts:378]: I would argue that this is needed, i tested and it help sync the frontend to update the active model immediately after the profile change instead of after the model response

**Comment by ivanarifin** [comment]
@mcowger i've made some minor changes to the ui virtual quota fallback provider presentation, it now uses searchable select for the provider picking and I also hide the enable reasoning checkbox and the advanced settings since it will follow the setting of each provider profile. What do you think?

**Comment by mcowger** [comment]
Definitely makes sense to me

**Comment by adamhill** [comment]
LGTM 🚀

**Comment by ivanarifin** [comment]
@chrarnoldus final review?

**Comment by ivanarifin** [comment]
Sorry to keep bothering you @chrarnoldus, what's the verdict? Does this PR need more change?

**Comment by ivanarifin** [comment]
Hi @chrarnoldus ,

Sorry to ping you again, but I just wanted to send a quick, friendly reminder about this PR. I'm afraid it might have slipped your mind!

I know it's not super urgent, but I personally use this feature about 90% of the time when I'm working with Kilo Code, so getting it merged would be a huge help and genuinely appreciated.

No rush at all, just checking in on the status. Thanks so much!

**Comment by chrarnoldus** [comment]
I will take a look when I have time. I don't think it needs further changes, but I would like to try it myself before merging.

**Comment by ivanarifin** [comment]
Understood, @chrarnoldus , thanks for the update.

I only checked in because I was worried the PR would get lost in the queue. Glad to hear you'll be trying it out!

**Comment by ivanarifin** [comment]
Fixes #1903  #1981 #1980

**Review by chrarnoldus — APPROVED** [review]
