### PR TITLE
Move MCP Servers button to settings

### LINKED ISSUE #73: Move MCP servers icon into settings
### Which version of the app are you using?

4.4.1

### Which API Provider are you using?

Kilo Code

### Which Model are you using?

Claude 3.7 Sonnet

### What happened?

This doesn't seem to be something that is more set & forget

### Steps to reproduce

1.
2.
3.

### Relevant API REQUEST output

```shell

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Juice10**
## Context

Moves MCP Servers to settings. Fixes #73

## Implementation

- Removes menu item from title bar (package.json)
- Added callback to `SettingsView` when MCP Servers is selected.
- Updated tests
- Fixed translation files 

## Screenshots

| before | after |
| ------ | ----- |
|    image    |    image   |

### CODE REVIEW

File: webview-ui/src/App.tsx [hunk 1]
```diff
@@ -96,7 +96,9 @@ const App = () => {
 			{tab === "prompts" && <PromptsView onDone={() => switchTab("chat")} />}
 			{tab === "mcp" && <McpView onDone={() => switchTab("chat")} />}
 			{tab === "history" && <HistoryView onDone={() => switchTab("chat")} />}
-			{tab === "settings" && <SettingsView ref={settingsRef} onDone={() => setTab("chat")} />}
+			{tab === "settings" && (
+				<SettingsView ref={settingsRef} onDone={() => setTab("chat")} onOpenMcp={() => setTab("mcp")} />
```
Comment (kevinvandijk) [inline webview-ui/src/App.tsx:101]: Instead of going back to the chat view, should we maybe go back to settings the regular settings once you click done in the MCP view since this is where you came from? Maybe this is fine, just thinking out loud.

**Review by kevinvandijk — CHANGES_REQUESTED** [review]
When trying it out I found a way to get the settings view to a blocked state. See attached gif (first run is how it works, then when you get a discard settings dialog, things get wonky when switching to the MCP view). I think that's something we should fix before merging this.

edit, wrong gif attached before, correct one now:
Monosnap screencast 2025-03-25 16-21-50

File: webview-ui/src/App.tsx (hunk 1 above)
Comment (Juice10) [reply webview-ui/src/App.tsx:101]: Done https://github.com/Kilo-Org/kilocode/pull/85/commits/ded0c3a736eb09daff00866be93f1f5710dc7851

**Comment by Juice10** [comment]
@kevinvandijk finally fixed the issue (doesn't get cleaner than this I'm afraid): https://github.com/Kilo-Org/kilocode/pull/85/commits/9e4af4984f2d9eaceb56aef88bd74327428d821a

**Review by kevinvandijk — APPROVED** [review]
