### PR TITLE
Replace email address by web address, because I don't believe in mailto

### LINKED ISSUE #1074: Mailto customer support does not trigger email client in Chrome
### Description

When trying to use the `feedback` button to send an email to customer support it opens a new blank instance of Google Chrome without opening any email apps.

**Steps to reproduce:**
- Click the "Feedback" button
- Click the "Customer Support" button
- Click the "Google Chrome" option
- A new blank instance of Google Chrome is shown without giving any options for email client (URL is blank)

When trying the above steps but selecting Firefox instead of Google Chrome it will open a new tab in an active Firefox instance and open a list of email options (URL has `mailto:hi@kilocode.ai`).

Tested on Windows 11 machine running Kilocode (Version: 4.49.3 (546244f4)) in WSL.

### PR DESCRIPTION
**Pull request by chrarnoldus**
Since desktop email apps are a 90s thing, I find it hard to believe many people have properly set up a mailto handler, so I think it's better to not rely on it.

Fixes https://github.com/Kilo-Org/kilocode/issues/1074

### CODE REVIEW

**Comment by kevinvandijk** [comment]
Instead of removing it, can we make it link to https://kilocode.ai/support ?
There's a contact form there plus an FAQ but we never link to it from the extension

File: src/core/webview/webviewMessageHandler.ts [hunk 1]
```diff
@@ -1326,7 +1326,7 @@ export const webviewMessageHandler = async (
 		case "showFeedbackOptions": {
 			const githubIssuesText = t("common:feedback.githubIssues")
 			const discordText = t("common:feedback.discord")
-			const customerSupport = t("common:feedback.customerSupport") // kilocode_change
+			const customerSupport = t("common:feedback.customerSupport")
```
Comment (kevinvandijk) [inline src/core/webview/webviewMessageHandler.ts:1329]: why remove the marker?

**Review by kevinvandijk — APPROVED** [review]

File: src/core/webview/webviewMessageHandler.ts (hunk 1 above)
Comment (chrarnoldus) [reply src/core/webview/webviewMessageHandler.ts:1329]: It already has `// kilocode_change start`
