### PR TITLE
Include changes from Roo Code v3.30.0

### LINKED ISSUE #2830: Chat  interface  checkpoint ui error
### Plugin Type

VSCode Extension

### App Version

4.99.0 ( and   the last 3 versions)

### Description

Image

### Reproduction steps

1) While working, receive an ‘API request not completed’ error in the chat.
2) Try to call up the checkpoint pop-up menu.
3) A menu will open that does not contain buttons for rolling back changes in the project.

### Provider

Claude Code

### Model

Sonnet 4/Sonnet 4.5

### System Information

Windows 11 / Debian 12 system

### LINKED ISSUE #3054: Provider Z.ai, model GLM-4.6 the setting Reasoning not avalaible ?
### Plugin Type

VSCode Extension

### App Version

v4.104.0

### Description

In

Provider Z.ai, model GLM-4.6 the setting Reasoning is not avalaible ?

### Reproduction steps

seelect provider 
select z.ai, no Reasoning

### Provider

_No response_

### Model

_No response_

### System Information

_No response_

### PR DESCRIPTION
**Pull request by chrarnoldus**

### CODE REVIEW

File: apps/web-roo-code/src/app/pr-fixer/PrFixerContent.tsx [hunk 1]
```diff
@@ -0,0 +1,240 @@
...
+import Image from "next/image"
+import Link from "next/link"
+
+import { Button } from "@/components/ui"
+import { AnimatedBackground } from "@/components/homepage"
+import { EXTERNAL_LINKS } from "@/lib/constants"
+import { trackGoogleAdsConversion } from "@/lib/analytics/google-ads"
+
+// Workaround for next/image choking on these for some reason
+const hero = "hero" // kilocode_change from: import hero from "/public/heroes/agent-pr-fixer.png"
```
Comment (chrarnoldus) [inline apps/web-roo-code/src/app/pr-fixer/PrFixerContent.tsx:13]: no idea why this fails for us, but it's not a priority to investigate it.

**Review by hassoncs — APPROVED** [review]
Everything looks reasonable to me. I'm curious if the search and replace removal will change anything 🤷‍♂️  I pulled it down and ran it locally today for a couple hours and didn't run into any issues

**Review by hassoncs — APPROVED** [review]
Everything looks reasonable to me. I'm curious if the search and replace removal will change anything 🤷‍♂️  I pulled it down and ran it locally today for a couple hours and didn't run into any issues

**Review by kevinvandijk — APPROVED** [review]

**Comment by mcowger** [comment]
> Everything looks reasonable to me. I'm curious if the search and replace removal will change anything 🤷‍♂️ I pulled it down and ran it locally today for a couple hours and didn't run into any issues

Search and replace is the only tool available if the user disabled "editing with diffs" in the advanced profile options.
