### PR TITLE
Fix 'failure to apply changes' when Git diff views are open

### LINKED ISSUE #712: Repeated failure to apply changes to files
### Description

Context:
- Version: Kilo Code 4.34.1 (db5a3095), Vscode: 1.100.3
- OS: Linux (Debian Sid), though accessed through SSH from macos
- Provider: Claude 3.7 Sonnet (the default)
- "Enable editing through diffs" is enabled with precision 100% (I think this is the default. I don't remember changing this. I have not tried switching it off, since I didn't realize there was such an option.)

Kilocode regularly gets into a loop trying and failing again and again to make a change to a file. The changes don't appear to be anything special or big. It usually recovers on its own, but it takes quite some attempts and wastes resources. 

Below is one example: 

```
I will now apply the fix.



The apply_diff failed because my view of crate/realize-lib/src/storage/real.rs is out of sync. I will read the file again to get its current content and then re-apply the fix to the subscribe function call.

I will now read the file.


Kilo Code wants to read this file:


I have read the latest version of crate/realize-lib/src/storage/real.rs. I will now re-apply the fix to the subscribe function call, adding the catchup parameter. After this, I will address the remaining error in crate/realize-lib/src/storage/real/history.rs.

I will now apply the fix.


Kilo Code wants to edit this file:

Edit Unsuccessful



The apply_diff failed again. It seems my view of crate/realize-lib/src/storage/real.rs is still not up-to-date. I will read the file one last time to ensure I have the correct content before applying the fix.

I will now read the file.


Kilo Code wants to read this file:


I have read the latest version of crate/realize-lib/src/storage/real.rs. It appears my previous change was not applied correctly. I will now re-apply the fix to the subscribe function, ensuring the catchup parameter is correctly passed to the history::subscribe function.

I will now apply the fix.


Kilo Code wants to edit this file:

Edit Unsuccessful


Kilo Code is having trouble...
This may indicate a failure in the model's thought process or inability to use a tool properly, which can be mitigated with some user guidance (e.g. "Try breaking down the task into smaller steps").



It appears my view of the files is still out of sync, causing the apply_diff operations to fail. To resolve this, I will read both crate/realize-lib/src/storage/real.rs and crate/realize-lib/src/storage/real/history.rs again to get their current content. Once I have the correct content, I will proceed with applying the necessary changes to implement the "catch up" feature.

I will now read the files.
```

### PR DESCRIPTION
**Pull request by hassoncs**
## Bug Description

`apply_diff` tool would fail consistently when Git diff views were open in VSCode.

## Root Cause

The bug was caused by **environment context contamination** in `src/core/environment/getEnvironmentDetails.ts`. When Git diff views are open, the environment details gathering code was incorrectly processing non-text tabs:

1. **Improper type casting**: Line 68 used `(tab.input as vscode.TabInputText)?.uri?.fsPath` without filtering, casting all tab inputs as `TabInputText` regardless of their actual type
2. **Processing incompatible tab types**: Git diff tabs have input types like `TabInputTextDiff`, not `TabInputText`
3. **Malformed environment data**: This resulted in unexpected/malformed data being included in the environment context sent to the AI
4. **AI parsing interference**: The contaminated context affected how the AI parsed multi-file `apply_diff` requests, causing them to fail

## Fix

Added proper tab type filtering before processing:

```typescript
// Before (BROKEN)
.map((tab) => (tab.input as vscode.TabInputText)?.uri?.fsPath)

// After (FIXED)
.filter((tab) => tab.input instanceof vscode.TabInputText)
.map((tab) => (tab.input as vscode.TabInputText).uri.fsPath)
```

This matches the correct pattern already used in other parts of the codebase like `DiffViewProvider.ts` and `WorkspaceTracker.ts`.

## Impact

- Multi-file edits now work reliably when Git diff views are open
- Environment context data is properly filtered and type-safe
- Consistent tab processing across the codebase

Fixes: https://github.com/Kilo-Org/kilocode/issues/712
Roo PR: https://github.com/RooCodeInc/Roo-Code/pull/6350

### CODE REVIEW

**Review by kevinvandijk — APPROVED** [review]

File: src/core/environment/getEnvironmentDetails.ts [hunk 1]
```diff
@@ -65,7 +65,8 @@ export async function getEnvironmentDetails(cline: Task, includeFileDetails: boo
 	const maxTabs = maxOpenTabsContext ?? 20
 	const openTabPaths = vscode.window.tabGroups.all
 		.flatMap((group) => group.tabs)
-		.map((tab) => (tab.input as vscode.TabInputText)?.uri?.fsPath)
+		.filter((tab) => tab.input instanceof vscode.TabInputText)
+		.map((tab) => (tab.input as vscode.TabInputText).uri.fsPath)
```
Comment (chrarnoldus) [inline src/core/environment/getEnvironmentDetails.ts:69]: kilocode_change?
