### PR TITLE
Fix overflowing text

### LINKED ISSUE #187: LLM model name text overflow issue in prompt area
### Which version of the app are you using?

4.14.2

### Which API Provider are you using?

Kilo Code

### Which Model are you using?

Claude 3.7

### What happened?

Image

Expected the model name not to impact the prompting area.

When using an LLM with a long model name, it overflows the bounding box of the prompt area and affects the button positions. Fix with concatenating long model numbers with three dots. You can then mouse over to see the full number if needed without breaking the design. 

### Steps to reproduce

1. In the Kilo Code extension the model number overflows the boundary of the border line.
2.
3.

### Relevant API REQUEST output

```shell

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kevinvandijk**
- Resolves #187

image

### CODE REVIEW

**Comment by EamonNerbonne** [comment]
screenshot?

**Review by EamonNerbonne — APPROVED** [review]

File: webview-ui/src/components/chat/ChatTextArea.tsx [hunk 1]
```diff
@@ -1104,8 +1105,10 @@ const ChatTextArea = forwardRef<HTMLTextAreaElement, ChatTextAreaProps>(
 						</div>
 
 						{/* kilocode_change begin: Model display */}
-						<div className="flex items-center mx-2">
-							<span className="text-xs text-vscode-descriptionForeground opacity-70">
+						<div
+							className="flex items-center mx-2 overflow-hidden"
+							title={`${selectedProvider}:${selectedModelId}`}>
+							<span className="text-xs text-vscode-descriptionForeground opacity-70 truncate">
```
Comment (EamonNerbonne) [inline webview-ui/src/components/chat/ChatTextArea.tsx:1111]: if it's just text, maybe ellipsis reads better?

Comment (kevinvandijk) [reply webview-ui/src/components/chat/ChatTextArea.tsx:1111]: The Tailwind [truncate](https://tailwindcss.com/docs/text-overflow) class adds ellipsis automatically. Added a screenshot to the PR to display
